navikt/helsearbeidsgiver-inntektsmelding

- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/serializers/UuidSerializer.kt
- helsebro/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/helsebro/HelsebroLøser.kt
- helsebro/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/helsebro/TrengerForespurtData.kt
- helsebro/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/helsebro/HelsebroLøserTest.kt
- helsebro/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/helsebro/PriProducerTest.kt
- helsebro/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/helsebro/TrengerForespurtDataTest.kt
Co-authored-by: Marte Tårnes <marte.tarnes@nav.no>
Co-authored-by: Gustav Berggren <gustav.berggren@nav.no>
Co-authored-by: Mikael Bjerga <mikael.bjerga@nav.no>
> Tar med vedtaksperiodeId i ForespurtData

- aareg/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/aareg/ArbeidsforholdMapper.kt
- api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/innsending/InnsendingRequest.kt
- api/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/TestData.kt
- api/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/innsending/GyldigData.kt
- api/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/innsending/InnsendingRequestTest.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/Arbeidsforhold.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/Periode.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/rapidsrivers/pritopic/Pri.kt
- forespoersel-mottatt/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/forespoerselmottatt/ForespoerselMottattLøser.kt
- helsebro/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/helsebro/ForespoerselSvarLøser.kt
- helsebro/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/helsebro/domene/ForespoerselSvar.kt
- helsebro/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/helsebro/ForespoerselSvarLøserTest.kt
- helsebro/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/helsebro/MockUtils.kt
Co-authored-by: Marte Tårnes <marte.tarnes@nav.no>
Co-authored-by: Mikael Bjerga <mikael.bjerga@nav.no>
> Legg til sykmeldingsperioder i ForespørselSvar

- db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/LagreJournalpostIdLøser.kt
- db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/PersisterImLøser.kt
- db/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/LagreJournalpostIdLøserTest.kt
- db/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/PersisterImLøserTest.kt
- distribusjon/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/distribusjon/DistribuerIMLøser.kt
- distribusjon/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/distribusjon/InntektsmeldingJournalførtListener.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/rapidsrivers/EventListener.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/rapidsrivers/Løser.kt
- joark/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/JournalfoerInntektsmeldingMottattListener.kt
- joark/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/JournalførInntektsmeldingLøser.kt
- joark/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/JournalfoerInntektsmeldingMottattListenerTest.kt
- notifikasjon/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/NotifikasjonInntektsmeldingMottattListener.kt
- notifikasjon/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/NotifikasjonLøser.kt
- notifikasjon/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/NotifikasjonLøserTest.kt
Thin implementation av Command og Listener pattern.
> Thin layer på topen av Listener og Command

- brreg/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/brreg/VirksomhetLøser.kt
- db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/LagreJournalpostIdLøser.kt
- db/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/LagreJournalpostIdLøserTest.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/Key.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/rapidsrivers/Løser.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/InnsendingIT.kt
Løsning er ikke i bruk i OppdaterJournalPostløseren plus noe andre små greie
> noe refaktorering

- config/aareg/dev-gcp.yml
- config/aareg/prod-gcp.yml
- config/akkumulator/dev-gcp.yml
- config/akkumulator/prod-gcp.yml
- config/altinn/dev-gcp.yml
- config/altinn/prod-gcp.yml
- config/api/dev-gcp.yml
- config/brreg/dev-gcp.yml
- config/brreg/prod-gcp.yml
- config/inntekt/dev-gcp.yml
- config/inntekt/prod-gcp.yml
- config/joark/dev-gcp.yml
- config/joark/prod-gcp.yml
- config/nais.yml
- config/notifikasjon/dev-gcp.yml
- config/notifikasjon/prod-gcp.yml
- config/pdl/dev-gcp.yml
- config/pdl/prod-gcp.yml
* skriv om nais.yml for å håndtere accesspolicy
> Legg til prod-konfig for diverse apper som snakker med eksterne tjenester

- aareg/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/inntekt/ArbeidsforholdLøserTest.kt
- api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/mapper/ResultatMapper.kt
- api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/tilgang/TilgangProducer.kt
- brreg/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/brreg/VirksomhetLøserTest.kt
- db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/LagreJournalpostIdLøser.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/Fail.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/Key.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/Løsning.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/Resultat.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/rapidsrivers/EventListener.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/utils/MapUtils.kt
- innsending/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/innsending/App.kt
- innsending/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/innsending/InnsendingService.kt
- innsending/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/innsending/TestCompositeEventListener.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/InnsendingIT.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/InnsendingServiceIT.kt
- joark/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/JournalfoerInntektsmeldingMottattListener.kt
- joark/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/JournalførInntektsmeldingLøser.kt
- joark/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/JournalførInntektsmeldingLøserTest.kt
Server genererte UUID-er for. UUID fjernet for journalføringen.  Transaksjon origin brukt istedenfor.
> infør TransaksjonOrigin og ta borte ubrukte løsning fra Journalføringen

- config/notifikasjon/dev-gcp.yml
- config/notifikasjon/prod-gcp.yml
Jeg fjernet også externalHosts da jeg forstår at dette ikke lenger behøves...
> Arbeidsgiver notifikasjon med service discovery

- felles-test/src/main/kotlin/no/nav/helsearbeidsgiver/felles/test/json/KotlinxUtils.kt
- felles-test/src/test/kotlin/no/nav/helsearbeidsgiver/felles/test/json/KotlinxUtilsKtTest.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/json/KotlinxUtils.kt
- felles/src/test/kotlin/no/nav/helsearbeidsgiver/felles/json/KotlinxUtilsKtTest.kt
> Legg til hjelpefunksjon i felles for å lese json

- aareg/build.gradle.kts
- api/build.gradle.kts
- felles/build.gradle.kts
- notifikasjon/build.gradle.kts
- pdl/build.gradle.kts
Det er ikke lenger noen direkte avhengigheter.
> Fjern eksludering av transitiv avhengighet fra tokenprovider

- dokument/src/main/resources/spesifikasjon.yaml
- joark/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/dokument/PdfDokument.kt
- joark/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/mappers/InntektEndringAarsakMapper.kt
- joark/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/dokument/PdfDokumentTest.kt
- joark/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/mappers/InntektEndringAarsakMapperTest.kt
- notifikasjon/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/OpprettOppgave.kt
Sykefravær, Feilregistrert og Nyansatt lagt til
> Nye verdier for inntektEndring årsak

- joark/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/dokument/PdfDokument.kt
- joark/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/dokument/PdfDokumentTest.kt
forrige commit kræsjet dersom ingen endring var satt!
> håndter ingen endringårsak i inntekt

- api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/innsending/InnsendingValidate.kt
- api/src/main/resources/messages_no.properties
- api/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/innsending/InnsendingRequestTest.kt
- api/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/innsending/InnsendingValidateKtTest.kt
- gradle.properties
Tidligere tillot vi kun inntekt > 0, nå tillater vi inntekt >= 0
> Inntekt kan være 0

- .github/workflows/prod.yml
Samme endring som i https://github.com/navikt/helsearbeidsgiver-inntektsmelding/pull/189.
> Bruk mer restriktiv tilgang i workflow for prodsetting

- akkumulator/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/akkumulator/HentNesteBehov.kt
- api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/validation/IsValidBehandlingsdager.kt
- build.gradle.kts
- gradle.properties
Denne brekker ktlint-workflowen, som det virker som ikke liker ..<-notasjonen som er innført i Kotlin 1.9.0. Jeg skal se på å oppgradere ktlint-versjonen vi bruker, men i mellomtiden så ser jeg ikke på dette som et stort problem.
> Bump Kotlin til 1.9.0

- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/rapidsrivers/RiverUtils.kt
Fikser en feil i https://github.com/navikt/helsearbeidsgiver-inntektsmelding/pull/198.
> Fiks logging av pakke

- gradle.properties
- pdl/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/pdl/App.kt
> Bruk PDL-klient med behandlingsgrunnlag

- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/utils/Messages.kt
Denne endringen løser ikke et stort problem i nåværende versjon av integrasjonstestene, siden "hovedtråden" (som leser meldinger) ikke gjør noe før (den antar) at rapid-tråden (som endrer meldinger) er ferdig med sitt. Problemet oppstår i https://github.com/navikt/helsearbeidsgiver-inntektsmelding/pull/188, da vi prøver å ikke så vente så lenge ved å sjekke underveis om rapid-tråden har kommet langt nok til at man kan validere innholder av meldingene som er publisert. Da kan man være midt i å undersøke meldingene så langt, når rapid-tråden legger til en ny, som fører til `ConcurrentModificationException`. Ved å forhindre samtidig tilgang ved å bruke en mutex-lås (https://kotlinlang.org/docs/shared-mutable-state-and-concurrency.html#mutual-exclusion) så løser vi problemet.
> Forhindre endring av meldinger samtidig som lesing

- helsebro/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/helsebro/ForespoerselSvarLøserTest.kt
Jeg vet ikke hvorfor denne ble kommentert ut, men det er ingenting galt med den 🤷
> Reaktiver test

- aareg/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/aareg/ArbeidsforholdLøser.kt
- aareg/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/inntekt/ArbeidsforholdLøserTest.kt
- aareg/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/inntekt/MockUtils.kt
- brreg/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/brreg/VirksomhetLøser.kt
- brreg/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/brreg/VirksomhetLøserTest.kt
- pdl/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/pdl/FulltNavnLøser.kt
- pdl/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/pdl/FulltNavnLøserTest.kt
> Ikke publiser løsning

- inntektservice/build.gradle.kts
- inntektservice/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/inntektservice/InntektService.kt
- inntektservice/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/inntektservice/InntektServiceTest.kt
- integrasjonstest/gradle.properties
- tilgangservice/build.gradle.kts
- tilgangservice/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/tilgangservice/TilgangService.kt
- tilgangservice/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/inntektservice/TilgangServiceTest.kt
Dette er ikke veldig elegant, mer et forslag til en kjapp fix i tilfelle dette smeller i prod også - vi kan diskutere / se gjennom sammen på fredag f eks
> kjapp og dirty fix og test for IllegalState i Inntekt og TilgangService

- api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/kvittering/KvitteringRoute.kt
- db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/MapInntektsmeldingDokument.kt
Unngår at pdf / xml tidspunkter blir i UTC
> reverser UTC, benytt system default

- joark/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/dokument/PdfDokument.kt
Endret fra innsendingstidspunkt
> PDF: bruk bestemmende fraværsdag som dato for lønn per mnd

- innsending/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/innsending/InnsendingService.kt
Plukk forespørselId fra packet, ikke fra redis
> InnsendingService: videresend forespørselId til alle løsere. 

- helsebro/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/helsebro/ForespoerselSvarLoeser.kt
`forespoerselId` finnes i `ForespoerselSvar`.
> Fjern warning for forespoersel-ID som finnes nestet

- notifikasjon/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/OpprettSakService.kt
Servicen er i en crash loop i prod fordi den prøver å lese forespørsel-ID fra Redis, som har timet ut, kombinert med en (alltid) uheldig `!!`.
> Forhindre crash loop i service for opprettelse av sak

- bro-spinn/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/brospinn/SpinnService.kt
- inntekt/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/inntekt/InntektLoeser.kt
- inntektservice/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/inntektservice/InntektService.kt
- tilgangservice/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/tilgangservice/TilgangService.kt
> les forespørselId fra packet, ikke redis, i tilgangservice og spinnservice

- db/gradle.properties
- db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/AapenImRepo.kt
- db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/ForespoerselRepository.kt
- db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/InntektsmeldingRepository.kt
Exposed gjør syntaxen til DSL-en mer lik SQL: https://github.com/JetBrains/Exposed/blob/main/docs/MIGRATION_GUIDE.md#migrating-from-0450-to-0460 🎉 
Sniker med noen andre, enkle forbedringer.
> Bump Exposed til 0.46.0

- config/bro-spinn/prod-gcp.yml
Merges inn så fort vi er live på ny app
> bro-spinn: endrer URL til spinosaurus i prod

- .github/workflows/prod.yml
> Bump workflows-avhengigheter

- joark/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/dokument/PdfDokumentTest.kt
> Formatering av lange navn i pdf - ny inntektsmelding.

- notifikasjon/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/river/OpprettSelvbestemtSakRiver.kt
Vi forventer behov, så vi burde ikke avvise det.
> Selvbestemt: Fiks lesing av melding for opprettelse av sak

- .github/workflows/integrasjonstest.yml
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast
> Fortsett resterende integrasjonstester om noen feiler

- api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/RedisPoller.kt
- api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/kvittering/KvitteringRoute.kt
- api/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/kvittering/KvitteringRouteKtTest.kt
- innsending/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/innsending/KvitteringService.kt
Nåværende implementasjon ignorerer feilmelding fra service.
> Kvittering: Les feilmelding

- api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/trenger/HentForespoerselResponse.kt
- api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/trenger/TrengerRoute.kt
- api/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/trenger/TrengerRouteKtTest.kt
> Gi frontend felt som sier om forespørsel er besvart

- api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/aktiveorgnr/AktiveOrgnrRoute.kt
- api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/innsending/InnsendingRoute.kt
- api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/inntekt/InntektRoute.kt
- api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/inntektselvbestemt/InntektSelvbestemtRoute.kt
- api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/kvittering/KvitteringRoute.kt
- api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/trenger/TrengerRoute.kt
Fjerner `route(...)`-blokken der den ikke trengs. Alt annet er whitespace.
> Fjern unødvendig route-blokk

- selvbestemt-lagre-im-service/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/selvbestemtlagreimservice/LagreSelvbestemtImService.kt
Litt YOLO-kode, men tanken er å kunne raskt greppe loggene for å få oversikt over omfanget nå i starten
> selvbestemt: logg warn hvis sykmelding er fram i tid

- altinn/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/altinn/AltinnRiver.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/loeser/ObjectRiver.kt
Det var kun AltinnRiver som manglet det.
Sniker også med noe småplukk:
- loggfelt blir påkrevd
- loggfelt blir tåler feil
- tomme meldinger publiseres ikke (det skal heller aldri ha forekommet)
> Krev feilhåndtering i alle ObjectRivers

- config/altinn/dev-gcp.yml
- config/nais.yml
sjekker inn maskinporten config i en egen PR.
> MaskinportenConfig

- berik-inntektsmelding-service/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/berikinntektsmeldingservice/BerikInntektsmeldingService.kt
- berik-inntektsmelding-service/src/test/kotlin/no.nav.helsearbeidsgiver.inntektsmelding.berikinntektsmeldingservice/BerikInntektsmeldingServiceTest.kt
- db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/river/LagreJournalpostIdRiver.kt
- db/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/river/LagreJournalpostIdRiverTest.kt
- felles/src/testFixtures/kotlin/no/nav/helsearbeidsgiver/felles/test/json/KotlinxUtils.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/BerikInntektsmeldingServiceIT.kt
- joark/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/JournalfoerImRiver.kt
- joark/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/JournalfoerImRiverTest.kt
Leser og videresender IM på nytt format som et forberedende steg til å ta i bruk ny IM-klasse i flere rivers.
> Videresend inntektsmelding på nytt format

- distribusjon/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/distribusjon/DistribusjonRiver.kt
- distribusjon/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/distribusjon/DistribusjonRiverTest.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/InnsendingIT.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/LagreSelvbestemtIT.kt
- joark/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/JournalfoerImRiver.kt
Vi ønsker å bruke ny IM-klasse overalt. Nå er det distribusjon sin tur.
> Bruk ny IM-klasse i distribusjonsapp

- berik-inntektsmelding-service/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/berikinntektsmeldingservice/BerikInntektsmeldingService.kt
- berik-inntektsmelding-service/src/test/kotlin/no.nav.helsearbeidsgiver.inntektsmelding.berikinntektsmeldingservice/BerikInntektsmeldingServiceTest.kt
- db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/river/LagreImRiver.kt
- db/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/river/LagreImRiverTest.kt
- db/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/river/LagreJournalpostIdRiverTest.kt
- joark/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/JournalfoerImRiverTest.kt
Vi ønsker å bruke ny IM-klasse overalt. Nå er det lagring av lagring av IM sin tur (kun melding).
> Les ny IM-klasse under lagring av inntektsmelding

- api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/innsending/InnsendingProducer.kt
- api/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/InnsendingProducerTest.kt
- innsending/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/innsending/InnsendingService.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/InnsendingServiceIT.kt
- joark/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/JournalfoerImRiver.kt
- joark/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/JournalfoerImRiverTest.kt
- selvbestemt-lagre-im-service/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/selvbestemtlagreimservice/LagreSelvbestemtImService.kt
- selvbestemt-lagre-im-service/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/selvbestemtlagreimservice/LagreSelvbestemtImServiceTest.kt
Vi har gjort om på hva som sendes/kreves hvor. Disse feltene er ikke lenger i bruk og kan derfor fjernes.
> Fjern utdaterte meldingsfelt

- integrasjonstest/build.gradle.kts
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/HentForespoerselIT.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/HentSelvbestemtIT.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/utils/EndToEndTest.kt
> Legg til integrasjonstest for henting av selvbestemt IM

- berik-inntektsmelding-service/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/berikinntektsmeldingservice/BerikInntektsmeldingService.kt
- berik-inntektsmelding-service/src/test/kotlin/no.nav.helsearbeidsgiver.inntektsmelding.berikinntektsmeldingservice/BerikInntektsmeldingServiceTest.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/Key.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/BerikInntektsmeldingServiceIT.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/InnsendingIT.kt
> Fjern utdaterte meldingsfelt fra berik-inntektsmelding-service

- joark/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/JournalfoerImRiver.kt
- joark/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/TilDokumenter.kt
- joark/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/dokument/PdfBuilder.kt
- joark/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/dokument/PdfDokument.kt
- joark/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/dokument/Utils.kt
- joark/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/TilDokumenterKtTest.kt
- joark/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/dokument/PdfDokumentTest.kt
- joark/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/dokument/UtilsTest.kt
Vi ønsker å bruke ny klasse for IM overalt. Nå bytter vi fra gammel til ny klasse i koden som generer PDF til journalføring.
> Bruk ny IM-klasse for å lage PDF til journalføring

- gradle/wrapper/gradle-wrapper.properties
- gradlew
> Bump Gradle til 8.10.2

- config/db/prod-gcp.yml
- config/feil-behandler/prod-gcp.yml
- config/notifikasjon/prod-gcp.yml
Oppgradering av DB-tier for Notifikasjon-DB,IM-DB,Felibehandler-DB i prod.
> Oppgraderer DB-tier

- config/nais.yml
I et forsøk på å få tilbake Grafana-metrikkene våre så tyr jeg til en ny måte å måle på.
Fjerner noe gammelt ræl fra nais-konfigen i samme slengen.
> Legger til autoinstrumentasjon med OpenTelemetry

- api/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/innsending/InnsendingRouteKtTest.kt
- innsending/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/innsending/InnsendingService.kt
- innsending/src/test/kotlin/no.nav.helsearbeidsgiver.inntektsmelding.innsending/InnsendingServiceTest.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/InnsendingServiceIT.kt
Vi bryr oss egentlig ikke om hva som er i svaret, bare at det er suksess, så jeg bytter til enklere data.
> Innsending: Skriv forespoersel-ID til Redis som svar til API

- db/src/main/resources/db/migration/V17__inntektsmelding_drop_contraint_fk.sql
Tabellen som foreign keyen går mot (se migrasjon V7) skal fjernes.
> Fjern krav om foreign key for inntektsmelding-tabell

- notifikasjon/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/App.kt
- notifikasjon/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/river/FjernPaaminnelseRiver.kt
- notifikasjon/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/river/FjernPaaminnelseRiverTest.kt
Vi ønsker å fjerne påminnelser fra oppgaver, men funksjonaliteten vi trenger i notifikasjons-APIet for å gjøre dette er ikke helt klar ennå.
> Legg til river som på sikt skal fjerne påminnelser fra oppgaver

- config/api/dev-gcp.yml
- config/api/prod-gcp.yml
- config/nais.yml
Simba-appene har for lite minne hvis man ser på bruken: https://metabase.ansatt.nav.no/dashboard/2-kubernetes-ressursbruk-team?cluster=prod-gcp&team=helsearbeidsgiver&periode=past7days~
Sniker med litt generell rydding i nais-yamlen.
> Øk minne for hver app

- inntektservice/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/inntektservice/App.kt
- inntektservice/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/inntektservice/InntektService.kt
- inntektservice/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/inntektservice/InntektServiceTest.kt
- tilgangservice/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/tilgangservice/App.kt
- tilgangservice/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/tilgangservice/TilgangForespoerselService.kt
- tilgangservice/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/inntektservice/TilgangForespoerselServiceTest.kt
Begge disse har serielle steg, så man kan ha dem som stateless.
> Bytt to servicer til stateless

- config/notifikasjon/dev-gcp.yml
Bruk hodet, vi har bare én klode.
> Vent ti minutter før vi sender ut påminnelser på oppgaver i dev

- config/notifikasjon/dev-gcp.yml
- notifikasjon/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/ArbeidsgiverNotifikasjonKlientUtils.kt
- notifikasjon/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/river/OpprettForespoerselSakOgOppgaveRiver.kt
- notifikasjon/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/ArbeidsgiverNotifikasjonKlientUtilsTest.kt
- notifikasjon/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/river/OpprettForespoerselSakOgOppgaveRiverTest.kt
Ta med sykmeldingsperioder i påminnelse varselet til arbeidsgiver.
Dermed blir det lettere for arbeidsgiver å forstå hvilken forespørsel eposten handler om.
> Legg på sykmeldingsperiode i påminnelse varselet

- config/db/dev-gcp.yml
- config/db/prod-gcp.yml
- config/feil-behandler/dev-gcp.yml
- config/feil-behandler/prod-gcp.yml
- config/nais.yml
- config/notifikasjon/dev-gcp.yml
- config/notifikasjon/prod-gcp.yml
Samler alt databaserelatert under en konfigvariabel.
> Rydder i naiskonfigformatet for database

- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/utils/DateUtils.kt
- forespoersel-mottatt/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/forespoerselmottatt/ForespoerselMottattRiver.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/ForespoerselMottattIT.kt
- joark/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/dokument/PdfDokument.kt
- joark/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/dokument/Utils.kt
- notifikasjon/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/ArbeidsgiverNotifikasjonKlientUtils.kt
- notifikasjon/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/HentDataTilSakOgOppgaveService.kt
- notifikasjon/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/river/OpprettForespoerselSakOgOppgaveRiver.kt
- notifikasjon/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/river/OpprettSelvbestemtSakRiver.kt
- notifikasjon/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/ArbeidsgiverNotifikasjonKlientUtilsTest.kt
- notifikasjon/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/HentDataTilSakOgOppgaveServiceTest.kt
- notifikasjon/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/river/OpprettForespoerselSakOgOppgaveRiverTest.kt
- notifikasjon/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/river/OpprettSelvbestemtSakRiverTest.kt
Dette skal gjøre det lettere for AG å skille saker på samme person.
> Vis sykmeldingsperioder som tilleggsinfo på sak

- config/nais.yml
- config/notifikasjon/dev-gcp.yml
- config/notifikasjon/prod-gcp.yml
Dette er en forberedelse til å slette notifikasjonsdatabasen, som ikke trengs lenger.
> Skru på cascading delete for notifikasjondatabase

- db/src/main/resources/db/migration/V18__forespoersel_drop_table.sql
Tabellen er ikke lenger i bruk.
> Slett tabell for forespørsler

- bro-spinn/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/brospinn/HentEksternImRiver.kt
- bro-spinn/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/brospinn/SpinnService.kt
- bro-spinn/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/brospinn/HentEksternImRiverTest.kt
- bro-spinn/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/brospinn/SpinnServiceTest.kt
- db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/river/HentLagretImRiver.kt
- db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/river/LagreEksternImRiver.kt
- db/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/river/HentLagretImRiverTest.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/Key.kt
- innsending/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/innsending/KvitteringService.kt
Endring som skal gjøre keys enklere i fremtiden ved å bruke lowercase
> Endret key format for ekstern inntektsmelding

- bro-spinn/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/brospinn/HentEksternImRiver.kt
- bro-spinn/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/brospinn/SpinnService.kt
- bro-spinn/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/brospinn/HentEksternImRiverTest.kt
- bro-spinn/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/brospinn/SpinnServiceTest.kt
- db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/river/HentLagretImRiver.kt
- db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/river/LagreEksternImRiver.kt
- db/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/river/HentLagretImRiverTest.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/Key.kt
- innsending/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/innsending/KvitteringService.kt
Tatt bort midlertidlig Key som eksisterte for å unngå inflight problemer
> Fjernet overgangsnøkkel i en melding

- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/Key.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/rapidsrivers/RiverUtils.kt
- helsebro/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/helsebro/ForespoerselSvarRiverTest.kt
Har lagt til en midlertidlig key for å unngå inflight errors.
> Midlertidlig FORESPOERSEL_SVAR key lagt til

- db/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/river/LagreJournalpostIdRiverTest.kt
- distribusjon/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/distribusjon/DistribusjonRiverTest.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/Key.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/rapidsrivers/RiverUtils.kt
- joark/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/JournalfoerImRiverTest.kt
Slettet midlertidlig FORESPOERSEL_ID key da denne ikke lenger er nødvendig
> Slettet midlertidlig FORESPOERSEL_ID key

- berik-inntektsmelding-service/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/berikinntektsmeldingservice/BerikInntektsmeldingService.kt
- forespoersel-marker-besvart/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/forespoerselmarkerbesvart/MarkerForespoerselBesvartRiver.kt
- forespoersel-marker-besvart/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/forespoerselmarkerbesvart/MarkerForespoerselBesvartRiverTest.kt
- joark/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/JournalfoerImRiver.kt
- joark/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/JournalfoerImRiverTest.kt
> Les nested data fra melding om mottatt IM

- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/utils/Log.kt
Dette gjør det lettere å se hvilke loggfelt vi har lagt til selv.
> Bruk prefiks for loggfelt

- apps/distribusjon/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/distribusjon/DistribusjonRiver.kt
- apps/distribusjon/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/distribusjon/DistribusjonRiverTest.kt
Spinn leser ikke lenger feltene som fjernes.
> Fjern sending av gammelt IM-format til Spinn

- apps/api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/innsending/InnsendingProducer.kt
- apps/api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/innsending/InnsendingRoute.kt
- apps/api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/lagreselvbestemtim/LagreSelvbestemtImProducer.kt
- apps/api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/lagreselvbestemtim/LagreSelvbestemtImRoute.kt
- apps/api/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/InnsendingProducerTest.kt
- apps/api/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/lagreselvbestemtim/LagreSelvbestemtImProducerTest.kt
- apps/berik-inntektsmelding-service/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/berikinntektsmeldingservice/BerikInntektsmeldingService.kt
- apps/berik-inntektsmelding-service/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/berikinntektsmeldingservice/MapInntektsmelding.kt
- apps/berik-inntektsmelding-service/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/berikinntektsmeldingservice/BerikInntektsmeldingServiceTest.kt
- apps/db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/InntektsmeldingRepository.kt
- apps/db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/river/LagreImSkjemaRiver.kt
- apps/db/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/river/LagreImSkjemaRiverTest.kt
- apps/innsending/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/innsending/InnsendingService.kt
- apps/integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/BerikInntektsmeldingServiceIT.kt
- apps/integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/InnsendingIT.kt
- apps/integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/InnsendingServiceIT.kt
- apps/integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/LagreSelvbestemtIT.kt
- apps/selvbestemt-lagre-im-service/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/selvbestemtlagreimservice/LagreSelvbestemtImService.kt
Fjerner alle nullabilities og default som ikke er nødvendig ettersom overgangsfasen er over.
> Fjern overgangsfaselogikk for mottattfelt

- apps/api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/kvittering/KvitteringRoute.kt
Glemte å ta med feltet i PR-en som introduserte ny kvittering.
> Legg til tidspunkt for mottagelse i ny kvittering

- apps/altinn/gradle.properties
For å få med denne endringen: https://github.com/navikt/helsearbeidsgiver-altinn-client/pull/16
> Bump til nyeste AltinnClient for å fikse loggfeil

- README.md
- build.gradle.kts
Slettet utdatert informasjon i README 
Lagt til støtte for å hente ut aggregert dependency-rapport - kjøres med:
gradle allDependencies
> oppdatert README og aggregert dependency-rapport

- .github/workflows/integrasjonstest.yml
- .github/workflows/prod.yml
- .github/workflows/test.yml
Tar i bruk GAR i prod workflow
Problemet som er nenvt https://github.com/navikt/helsearbeidsgiver-inntektsmelding/pull/54 er fortsatt ikke løst.
Derfor har jeg tatt i bruk upload artifact action som er nevnt som workaround.
Vi er nødt til å gjøre dette fordi det blir obligatorisk med GAR fra 1. april [se kontext her](https://nav-it.slack.com/archives/C01DE3M9YBV/p1740396455823219).
> Bruk GAR i prod workflow

- .github/workflows/prod.yml
Fjern duplikat steg fra prod workflow
> Fiks feil i prod workflow fjern gammelt steg

- apps/berik-inntektsmelding-service/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/berikinntektsmeldingservice/BerikInntektsmeldingService.kt
- apps/berik-inntektsmelding-service/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/berikinntektsmeldingservice/BerikInntektsmeldingServiceTest.kt
- apps/db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/InntektsmeldingRepository.kt
- apps/db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/river/LagreImSkjemaRiver.kt
- apps/db/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/river/LagreImSkjemaRiverTest.kt
- apps/felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/Key.kt
- apps/innsending/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/innsending/InnsendingService.kt
- apps/innsending/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/innsending/api/ApiInnsendingService.kt
- apps/innsending/src/test/kotlin/no.nav.helsearbeidsgiver.inntektsmelding.innsending/InnsendingServiceTest.kt
- apps/innsending/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/innsending/api/ApiInnsendingServiceTest.kt
- apps/integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/InnsendingServiceIT.kt
- apps/joark/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/JournalfoerImRiver.kt
- apps/joark/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/JournalfoerImRiverTest.kt
- apps/joark/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/dokument/PdfDokumentTest.kt
Innsending-ID er erstattet av inntektsmelding-ID.
> Fjern utdatert innsending-ID

- apps/integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/utils/EndToEndTest.kt
- apps/notifikasjon/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/App.kt
- apps/notifikasjon/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/ArbeidsgiverNotifikasjonKlientUtils.kt
- apps/notifikasjon/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/Env.kt
- apps/notifikasjon/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/river/FjernPaaminnelseRiver.kt
- apps/notifikasjon/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/river/OpprettForespoerselSakOgOppgaveRiver.kt
- apps/notifikasjon/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/river/FjernPaaminnelseRiverTest.kt
- apps/notifikasjon/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/river/OpprettForespoerselSakOgOppgaveRiverTest.kt
- config/notifikasjon/dev-gcp.yml
- config/notifikasjon/prod-gcp.yml
Snublet over denne. Ser ut som togglen alltid er true.
> Fjern utdatert toggle

- apps/felles-auth/src/main/kotlin/no/nav/helsearbeidsgiver/felles/auth/AuthClient.kt
- config/aareg/dev-gcp.yml
- config/aareg/prod-gcp.yml
- config/altinn/dev-gcp.yml
- config/altinn/prod-gcp.yml
- config/api/dev-gcp.yml
- config/api/prod-gcp.yml
- config/bro-spinn/dev-gcp.yml
- config/bro-spinn/prod-gcp.yml
- config/brreg/dev-gcp.yml
- config/brreg/prod-gcp.yml
- config/db/dev-gcp.yml
- config/db/prod-gcp.yml
- config/feil-behandler/dev-gcp.yml
- config/feil-behandler/prod-gcp.yml
- config/inntekt/dev-gcp.yml
- config/inntekt/prod-gcp.yml
- config/joark/dev-gcp.yml
- config/joark/prod-gcp.yml
- config/nais.yml
- config/notifikasjon/dev-gcp.yml
- config/notifikasjon/prod-gcp.yml
- config/pdl/dev-gcp.yml
- config/pdl/prod-gcp.yml
Slår sammen noen sammenkoblede variabler, og fjerner noen overflødige variabler og innstillinger.
> Rydd i nais-konfig

- apps/db/src/main/resources/db/migration/V21__inntektsmelding_add_im_nytt_format.sql
Nytt felt `inntektsmelding` for IM på nytt format.
Lurer med felt `erProsessert` for å registrere IM-er som har fullført løypa gjennom Simba.
> Legg til nytt databasefelt for inntektsmelding

- .github/workflows/slett-pakker.yml
Vi har en haug med gamle pakker. Legger til en workflow som kan trigges manuelt for å slette disse. Er i det eksperimentelle stadiet, så kan kun slette pakker fra et begrenset antall apper til å begynne med.
> Legg til workflow for å slette gamle pakker

- apps/felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/kafka/Producer.kt
- apps/felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/rapidsrivers/RiverUtils.kt
- apps/felles/src/test/kotlin/no/nav/helsearbeidsgiver/felles/kafka/ProducerTest.kt
Tar ingen av de nye funksjonene i bruk enda. Det skjer i https://github.com/navikt/helsearbeidsgiver-inntektsmelding/pull/868.
> Utvid producer

- config/inntekt/dev-gcp.yml
- config/inntekt/prod-gcp.yml
Endrer til ny ingress + scope for inntektskomponenten ref https://nav-it.slack.com/archives/C07TJUV5ZS9/p1746001720169749
Ingen proxy nødvendig lenger, så derfor blir URL også litt annerledes enn tidligere.
Verifisert OK i dev
> ny inntekt ingress

- apps/db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/App.kt
- apps/db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/InntektsmeldingRepository.kt
- apps/db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/river/LagreImRiver.kt
- apps/db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/river/LagreJournalpostIdRiver.kt
- apps/db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/river/LagreSelvbestemtImRiver.kt
- apps/db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/river/OppdaterImSomProsessertRiver.kt
- apps/db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/tabell/InntektsmeldingEntitet.kt
- apps/db/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/InntektsmeldingRepositoryTest.kt
- apps/db/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/river/OppdaterImSomProsessertRiverTest.kt
- apps/feil-behandler/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/feilbehandler/river/FeilLytter.kt
- apps/felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/utils/Log.kt
Dersom en IM ikke er markert som prosessert så vet vi at den er et sted i Simba-løypa.
> Oppdater inntektsmelding som prosessert etter distribusjon

- apps/berik-inntektsmelding-service/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/berikinntektsmeldingservice/BerikInntektsmeldingService.kt
- apps/db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/river/LagreImSkjemaRiver.kt
- apps/distribusjon/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/distribusjon/DistribusjonRiver.kt
- apps/forespoersel-marker-besvart/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/forespoerselmarkerbesvart/MarkerForespoerselBesvartRiver.kt
- apps/innsending/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/innsending/api/ApiInnsendingService.kt
- apps/joark/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/JournalfoerImRiver.kt
Kan være nyttig for feilsøking i loggene.
> Logg inntektsmelding-ID underveis i mottak av inntektsmelding

- apps/db/src/main/resources/db/migration/V22__selvbestemt_add_prosessert.sql
Legger til samme kolonne som for forespurt inntektsmelding (https://github.com/navikt/helsearbeidsgiver-inntektsmelding/pull/871).
> Legg til nytt databasefelt for selvbestemt inntektsmelding

- apps/api/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/hentforespoersel/HentForespoerselRouteKtTest.kt
- apps/felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/domene/HentForespoerselResultat.kt
- apps/felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/rapidsrivers/redis/RedisStore.kt
- apps/felles/src/test/kotlin/no/nav/helsearbeidsgiver/felles/rapidsrivers/redis/RedisStoreTest.kt
- apps/integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/HentForespoerselIT.kt
- apps/trengerservice/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/trengerservice/HentForespoerselService.kt
- apps/trengerservice/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/trengerservice/HentForespoerselServiceTest.kt
Denne feilrapporteringen ble før sendt til frontend, men det gjør vi ikke lenger. Fjerner derfor koden rundt å opprette feilrapporteringen.
> Fjern utdatert feilrapportering

- apps/brreg/gradle.properties
- apps/brreg/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/brreg/App.kt
- apps/brreg/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/brreg/HentOrganisasjonNavnRiver.kt
- apps/brreg/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/brreg/HentOrganisasjonNavnRiverTest.kt
- apps/integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/AktiveOrgnrServiceIT.kt
- apps/integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/LagreSelvbestemtIT.kt
- apps/integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/utils/EndToEndTest.kt
Tar i bruk LocalCache, og klient med retry- og timeout-oppsett.
> Bruk siste versjon av Brreg-klient

- apps/api/http/oppdaterInntekt.http
- apps/api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/aktiveorgnr/AktiveOrgnrRequest.kt
- apps/api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/aktiveorgnr/AktiveOrgnrRoute.kt
- apps/api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/innsending/InnsendingResponse.kt
- apps/api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/inntekt/InntektRequest.kt
- apps/api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/inntekt/InntektRoute.kt
- apps/api/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/aktiveorgnr/AktiveOrgnrRouteKtTest.kt
- apps/api/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/inntekt/InntektRouteKtTest.kt
- apps/inntektservice/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/inntektservice/InntektService.kt
Frontend har tatt nye request-felt i bruk, så da kan de gamle fjernes.
> Erstatt utdaterte request-felt

- Dockerfile
- apps/notifikasjon/gradle.properties
Sniker med en fiks for språk i Dockerfile.
> Bruk AG-notifikasjon-klient med retry og timeout
