- gradle.properties
sikkerhetsfix - treffer egentlig kun der ktor-server serverer statisk innhold, men better safe than sorry
> oppgraderer ktor (CVE-2022-48476)

- .github/workflows/integrasjonstest.yml
Gjorde et lite eksperiment med å kjøre integrasjonstestene med kraftigere runners i Github Actions med følgende resultater:
* 2-core (standard) runner tok 10 min og 40 sek, se [eksempel](https://github.com/navikt/helsearbeidsgiver-inntektsmelding/actions/runs/5290867528/jobs/9575622492)
* 4-core runner (https://github.com/navikt/helsearbeidsgiver-inntektsmelding/pull/165) tok 9 min og 53 sek, se [eksempel](https://github.com/navikt/helsearbeidsgiver-inntektsmelding/actions/runs/5323342236/jobs/9641030282)
* 8-core runner (denne PR) tok 7 min og 18 sek, se [eksempel](https://github.com/navikt/helsearbeidsgiver-inntektsmelding/actions/runs/5309745094/jobs/9640203435)
* 16-core runner (https://github.com/navikt/helsearbeidsgiver-inntektsmelding/pull/163) tok 7 min og 10 sek, se …
> Bruk kraftigere workflow runner for integrasjonstest

- .github/workflows/build.yml
Bygger og deployer helt fint: https://github.com/navikt/helsearbeidsgiver-inntektsmelding/actions/runs/5472910091
Vi trenger `packages:write` for å pushe docker imaget.
> Bruk mer restriktiv tilgang i workflow for bygging

- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/Key.kt
- innsending/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/innsending/InnsendingService.kt
- innsending/src/test/kotlin/no.nav.helsearbeidsgiver.inntektsmelding.innsending/GenericDataPackageListenerTest.kt
- joark/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/dokument/UtilsTest.kt
Nytt i Kotlin 1.9.0: https://kotlinlang.org/docs/whatsnew19.html#stable-replacement-of-the-enum-class-values-function
> Bruk forbedret måte å lese alle enum-verdier

- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/app/LocalApp.kt
The old url is deprecated and will be removed soon.
> chore: update fakedings url

- altinn/gradle.properties
- altinn/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/altinn/AltinnLoeserTest.kt
Ved å slette den lokale versjonsspesifiseringen så brukes den globale, som bruker versjon 0.3.0 for Altinn-klienten.
> Bruk siste Altinn-klient for tilgangskontroll

- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/loeser/PacketSolver.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/rapidsrivers/DataKanal.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/rapidsrivers/EventListener.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/rapidsrivers/Loeser.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/rapidsrivers/StatefullDataKanal.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/rapidsrivers/composite/CompositeEventListener.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/rapidsrivers/model/Data.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/rapidsrivers/model/Fail.kt
- forespoersel-besvart/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/forespoerselbesvart/ForespoerselBesvartLoeser.kt
- forespoersel-marker-besvart/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/forespoerselmarkerbesvart/MarkerForespoerselBesvartRiver.kt
- forespoersel-mottatt/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/forespoerselmottatt/ForespoerselMottattLoeser.kt
- helsebro/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/helsebro/ForespoerselSvarLoeser.kt
- notifikasjon/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/OppgaveFerdigLoeser.kt
- notifikasjon/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/SakFerdigLoeser.kt
+ lagt til interestedIn på forespørselId i Data, Fail, packetSolver og ForespoerselBesvartLoeser
Det er litt mye duplisert kode, men tanken var egentlig bare å rulle ut dette og la det kjøre en stund i produksjon, for å se om vi egentlig har noen tilfeller der forespørselID IKKE sendes. 
Hvis vi er trygge på at vi alltid mottar forespørselId, kan vi vurdere å bare lese denne verdien rett fra packet, heller enn å lese fra en noe tvilsom redis.
> midlertidig logg warn om forespørselId ikke kommer i packet

- bro-spinn/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/brospinn/SpinnService.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/rapidsrivers/composite/CompositeEventListener.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/rapidsrivers/redis/RedisKey.kt
- innsending/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/innsending/InnsendingService.kt
- innsending/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/innsending/KvitteringService.kt
- inntektservice/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/inntektservice/InntektService.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/InnsendingServiceIT.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/KvitteringIT.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/TrengerIT.kt
- notifikasjon/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/ManuellOpprettSakService.kt
- notifikasjon/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/OpprettOppgaveService.kt
- notifikasjon/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/OpprettSakService.kt
- notifikasjon/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/OpprettSakServiceTest.kt
- tilgangservice/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/tilgangservice/TilgangService.kt
- trengerservice/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/trengerservice/TrengerService.kt
Endringene her startet som en innsats for å gjøre all bruk av RedisStore avhengig av RedisKey, men underveis oppdaget jeg at vi hadde en del skriving til redis som brukte feil nøkkel. Fikset disse i samme slengen, siden de var knyttet opp til lesing og skriving til redis. De endringene er færre linjer enn endringer på RedisKey, men de er viktigere, så de trumfet i commit- og PR-navn. I realiteten er PR-en en "herlig" blanding av RedisKey-endringer og endringer i nøkler brukt mot redis.
> Fullfør med korrekt ID i service

- notifikasjon/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/OpprettOppgaveService.kt
- notifikasjon/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/OpprettSakService.kt
Fikser crash loop i prod som oppstår etter lesing av utgåtte verdier fra Redis, kombinert med (alltid) uheldige `!!`.
> Forhindre crash loop i servicer for opprettelse av sak og oppgave

- aareg/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/aareg/ArbeidsforholdLoeser.kt
- aareg/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/inntekt/ArbeidsforholdLoeserTest.kt
- aktiveorgnrservice/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/aktiveorgnrservice/AktiveOrgnrService.kt
- altinn/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/altinn/AltinnLoeser.kt
- altinn/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/altinn/TilgangLoeser.kt
- altinn/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/altinn/AltinnLoeserTest.kt
- brreg/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/brreg/VirksomhetLoeser.kt
- feil-behandler/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/feilbehandler/river/FeilLytter.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/json/KotlinxUtils.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/loeser/ObjectRiver.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/rapidsrivers/RiverUtils.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/rapidsrivers/composite/CompositeEventListener.kt
- felles/src/test/kotlin/no/nav/helsearbeidsgiver/felles/json/KotlinxUtilsKtTest.kt
- forespoersel-besvart/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/forespoerselbesvart/ForespoerselBesvartFraSimbaLoeser.kt
- forespoersel-besvart/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/forespoerselbesvart/ForespoerselBesvartFraSpleisLoeser.kt
- forespoersel-besvart/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/forespoerselbesvart/ForespoerselBesvartLoeser.kt
- forespoersel-besvart/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/forespoerselbesvart/ForespoerselBesvartFraSpleisLoeserTest.kt
- forespoersel-mottatt/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/forespoerselmottatt/ForespoerselMottattLoeserTest.kt
- helsebro/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/helsebro/ForespoerselSvarLoeser.kt
- helsebro/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/helsebro/TrengerForespoerselLoeser.kt
- helsebro/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/helsebro/TrengerForespoerselLoeserTest.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/EksternInntektsmeldingLagretIT.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/InnsendingServiceIT.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/utils/EndToEndTest.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/utils/Messages.kt
- notifikasjon/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/OppgaveFerdigLoeser.kt
- notifikasjon/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/SakFerdigLoeser.kt
- trengerservice/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/trengerservice/TrengerService.kt
Bruken av IKey ble utstrakt når Simba sin interne rapid har nøkler som stammer fra Key eller Datafelt, som begge var IKey. Nå er det bare Key og Pri.Key som er IKey, og bruken bør snevres inn til mindre viktige funksjoner.
(Ved å beholde IKey så slipper vi noe duplisering av relativt få metoder som også er aktuelle for Pri.Key. Det kan vi alltids vurdere om vi vil beholde.)
> Erstatt utdatert bruk av IKey (stammer fra Datafelt)

- .github/workflows/build.yml
- .github/workflows/gradle-dependabot.yml
- .github/workflows/integrasjonstest.yml
- .github/workflows/prod.yml
- .github/workflows/test.yml
`gradle/gradle-build-action@v3` erstattes med `gradle/actions/setup-gradle@v3`. Se https://github.com/gradle/gradle-build-action/releases/tag/v3.0.0.
> Bump workflows-avhengigheter

- aktiveorgnrservice/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/aktiveorgnrservice/AktiveOrgnrService.kt
- brreg/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/brreg/VirksomhetLoeserTest.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/AktiveOrgnrServiceIT.kt
Det kunne oppstå en evig loop dersom henting av fullt navn på sykmeldt feilet, men det forhindres av ny if-sjekk i `inProgress`. 
I tillegg så har jeg lagt til lesing av publiserte feil, slik at servicen avbryter umiddelbart om noe går galt. Jeg har blitt enig med Kent om at det er best at man avbryter for alle typer publiserte feil, så det er ikke lagt til noen recover-logikk, som noen andre servicer har.
> Fiks potensiell evig loop i service

- forespoersel-marker-besvart/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/forespoerselmarkerbesvart/MarkerForespoerselBesvartRiver.kt
Dette burde ha vært med fra start, men potensielle konsekvenser har bare vært at forespørsler har blitt marker besvart to ganger rett etter hverandre, så det har ikke blitt oppdaget.
> Avvis meldinger med fail

- api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/innsending/InnsendingProducer.kt
- db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/river/PersisterImLoeser.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/Key.kt
- innsending/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/innsending/InnsendingService.kt
Klassen `Innsending` sendes under `Key.INNTEKTSMELDING`. Fare for å forveklse innholdet med klassen `Inntektsmelding`, så jeg gjør et lite bytte. Jeg gjør det også fordi jeg vil benytte nøkkelen til å sende klassen `Inntektsmelding`.
> Legg til erstatningskey i melding

- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/TrengerInntekt.kt
- felles/src/test/kotlin/no/nav/helsearbeidsgiver/felles/TrengerInntektTest.kt
- innsending/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/innsending/MapInntektsmelding.kt
- innsending/src/test/kotlin/no.nav.helsearbeidsgiver.inntektsmelding.innsending/MapInntektsmeldingKtTest.kt
- trengerservice/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/trengerservice/TrengerService.kt
Den forrige løsningen tok ikke hensyn til nye IM-er på allerede besvarte forespørsler som ble opprettet før Spleis sendte oss alle bestemmende fraværsdager.
> Beregn bestemmende fraværsdag dersom forslag fra Spleis mangler

- joark/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/dokument/Utils.kt
- joark/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/dokument/PdfDokumentTest.kt
- joark/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/dokument/UtilsTest.kt
**Bakgrunn**
Navn i PDFen kan være skrevet i store bokstaver og dermed kan 40 tegn, som er dagens maksbredde, overskride tilgjengelig bredde. 
**Løsning**
- Reduser til 36 tegn, som ser ut til å løse problemet gitt et "normalt" navn (navn med veldig mange Mer og Wer kan fortsatt overskride bredden). 
- Oppdaterer testen for innsendernavn til store bokstaver med 37 tegn.
- Jeg vurderer dette som en enklere løsning enn å begynne å tukle med store og små bokstaver i navnet, fordi stor bokstav i navn ikke nødvendigvis er helt rett frem (f.eks. med bindestrek-navn eller navn som ikke skal starte på stor bokstav).
| Før | Etter  | 
| ------- | --- | 
| <img width="614" alt="image" src="https://github.com/navikt/helsearbeidsgiver-inntektsmelding/assets/41949947/ae988eb4-0049-4619-a2f3-7c1daf9f373 …
> Reduser maks linjelengde for inntektsmelding-pdfer

- config/api/dev-gcp.yml
- config/api/prod-gcp.yml
- config/nais.yml
**Bakgrunn**
Fordi det er bestemt at ikke-utviklere ikke lenger skal ha tilgang til Nais-device, må frontenden flyttes ut av det clusteret som den deler med backenden i dag. Dermed må innkommende trafikk inn til backend eksplisitt tillates.
**Løsning**
Tillat innkommende trafikk fra `spinntektsmelding-frontend`.
> Tillat innkommende trafikk fra spinntektsmelding-frontend

- notifikasjon/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/App.kt
- notifikasjon/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/ArbeidsgiverNotifikasjonKlientUtils.kt
- notifikasjon/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/river/SakFerdigLoeser.kt
- notifikasjon/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/river/SakFerdigLoeserTest.kt
**Bakgrunn**
Oppgaver som er ferdig løst linker fortsatt til `/im-dialog/{forespørselId}`, som etterhvert sender bruker videre til `/im-dialog/{forespørselId}`. Når en sak er ferdig løst kan vi sende brukeren direkte til kvitteringssiden sånn at han slipper et unødvendig pitstop innom `/im-dialog/{forespørselId}`.
**Løsning**
Endre sakens lenke til å peke på kvitteringssiden når en oppgave blir markert som ferdig.
> Endre link i sak til å peke på kvitteringsside når man sender inn inntekstmelding

- config/pdl/dev-gcp.yml
**Bakgrunn**
I dag har vi en egen proxytjeneste i helse arbeidsgiver for kommunikasjon mot pdl. Denne er vi interessert i å fase ut bruken av.
**Løsning**
Etter at vi har fått tilgang til pdl sitt api fra `im-pdl` i dev i https://github.com/navikt/pdl/pull/2722, så kan vi nå kommunisere med pdl uten å gå gjennom proxytjenesten vår (heller gjennom proxytjenesten til pdl).
> Slutt å bruke vår egen proxytjeneste for å kommunisere med pdl i dev

- config/pdl/dev-gcp.yml
- config/pdl/prod-gcp.yml
- pdl/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/pdl/Environment.kt
Etter denne (https://github.com/navikt/pdl/commit/b0d860a10b88bbfea7c66fa29d1a8775e647a051) endringen i PDL, så skal vi nå kunne slutte å bruke vår egen proxy for å kommunisere med PDL i prod.
> Slutt å bruke vår egen proxy for kommunikasjon med pdl i prod

- .github/workflows/build.yml
- .github/workflows/prod.yml
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
Lager to deploy-grupper: én for dev og én for prod. For hver gruppe kan man ha en deploy-jobb kjørende. Dersom en ny deploy-jobb skulle bli satt i gang så vil den settes på vent. Hvis enda en deploy-jobb skulle bli satt i gang så vil den ventende jobben kanselleres og den nyeste jobben overta venteposisjonen. Når den kjørende jobben er ferdig så vil den ventende jobben kjøres.
Legger dette til slik at vi unngår flere sammenfiltrede deploys, der vi ender opp med en situasjon der noen apper stammer fra jobb A og noen stammer fra jobb B. Denne tilstanden kan selvfølgelig oppstå uansett, men nå er det litt mindre sannsynlig.
> Forhindre samtidige deploys til et miljø

- aareg/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/aareg/Environment.kt
- config/aareg/dev-gcp.yml
- config/aareg/prod-gcp.yml
- gradle.properties
**Bakgrunn**
Vi ønsker å slutte og bruke vår egen proxy (https://github.com/navikt/helsearbeidsgiver-proxy/tree/master) når vi kommuniserer med Aareg.
**Løsning**
1. Bytt ut Aareg url, scope og external hosts i dev og prod.
2. Ta i bruk nyeste versjon (0.7.0) av aareg-client, hvor Nav-Consumer-Token ikke lenger sendes med (https://github.com/navikt/helsearbeidsgiver-aareg-client/pull/6).
> Slutt å bruke vår egen proxy for å kommunisere med Aareg 

- .github/workflows/integrasjonstest.yml
- .github/workflows/test.yml
https://github.com/gradle/actions/blob/main/docs/deprecation-upgrade-guide.md#using-the-action-to-execute-gradle-via-the-arguments-parameter-is-deprecated
> Erstatt utdatert parameter i workflows

- .github/workflows/build.yml
- .github/workflows/prod.yml
Gjør et nytt forsøk fordi `concurrency` ikke fungerte som forventet sammen med `matrix`.
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
Lager to deploy-grupper **per app**: én for dev og én for prod. For hver gruppe kan man ha en deploy-jobb kjørende. Dersom en ny deploy-jobb skulle bli satt i gang så vil den settes på vent. Hvis enda en deploy-jobb skulle bli satt i gang så vil den ventende jobben kanselleres og den nyeste jobben overta venteposisjonen. Når den kjørende jobben er ferdig så vil den ventende jobben kjøres.
Legger dette til slik at vi unngår flere sammenfiltrede deploys, der vi ender opp med en situasjon der noen apper stammer fra jobb A og noen stammer fra jobb B. Denne tilstanden kan selvfølgelig oppstå uansett, men nå er …
> Forhindre samtidige deploys til et miljø (v2)

- api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/innsending/InnsendingRoute.kt
- innsending/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/innsending/InnsendingService.kt
**Bakgrunn**
Vi ønsker å gjøre innsending raskere, og vil ha på plass en metrikk og litt ekstra logging før vi setter i gang med tiltak.
**Løsning**
Legg til metrikk for innsendingsendepunkt som kan legges inn i Grafana-grafene våre, så samme måte som i `KvitteringRoute`.
Bonus: Legg til en ekstra logglinje i `InnsendingsService` sin `inProgress`-metode for å kunne danne et bilde av hvor lang tid "hent forespørsel"-delen av innsendingen tar (ved å se på tidsdifferansen mellom logglinja `InnsendingService: emitting behov HENT_TRENGER_IM` og den nye logglinja).
> Legg til metrikk for responstid ved innsending av inntektsmelding

- config/joark/dev-gcp.yml
- config/joark/prod-gcp.yml
- joark/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/Env.kt
Det viste seg at im-joark allerede er lagt inn med tilgang til dokarkiv
https://github.com/navikt/dokarkiv/blob/930b88c062345c253fa60c7e96cbbdba42a2eb6b/nais/p-config.json#L181-L183
Så tenker det er greit å bytte så kan vi kvitte oss med helsearbeidsgiver-proxy snart.
Testet ok i dev
> Bytt fra vår proxy til dokarkiv proxy

- api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/inntektselvbestemt/InntektSelvbestemtProducer.kt
- api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/trenger/TrengerProducer.kt
- api/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/inntektselvbestemt/InntektSelvbestemtProducerTest.kt
- api/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/trenger/TrengerProducerTest.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/rapidsrivers/service/Service.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/rapidsrivers/service/ServiceMelding.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/rapidsrivers/service/ServiceRiver.kt
- felles/src/test/kotlin/no/nav/helsearbeidsgiver/felles/rapidsrivers/service/ServiceRiverTest.kt
- inntekt-selvbestemt-service/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/inntektselvbestemtservice/InntektSelvbestemtService.kt
- inntekt-selvbestemt-service/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/inntektselvbestemtservice/InntektSelvbestemtServiceTest.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/InntektSelvbestemtIT.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/TrengerIT.kt
- trengerservice/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/trengerservice/TrengerService.kt
Nå som ServiceRiver ikke lenger har client-ID eller genererer ny transaksjon-ID ved startmelding så kan håndtering av startmelding forenkles til noe nærmere en datamelding.
> Forenkle startsteg i ServiceRiver

- api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/hentselvbestemtim/HentSelvbestemtImRoute.kt
- api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/lagreselvbestemtim/LagreSelvbestemtImRoute.kt
- api/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/hentselvbestemtim/HentSelvbestemtImRouteKtTest.kt
- api/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/lagreselvbestemtim/LagreSelvbestemtImRouteKtTest.kt
Fire inntektsendringsårsaker hadde før et felt som het "perioder". Det heter nå noe spesifikt til årsaken, men endringen er ikke gjennomført i frontend. Det kom ikke frem under testing. Jeg lagde en enkel, men litt grisete fiks på backenden slik at den tåler begge deler. Tanken er at det kan fikses i frontend når frontendteamet kommer hjem fra sin felles ferie.
> Midlertidig: Tål gammelt format på årsak for inntektsendring

- bro-spinn/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/brospinn/App.kt
- bro-spinn/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/brospinn/EksternInntektsmeldingLoeser.kt
- bro-spinn/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/brospinn/HentEksternImRiver.kt
- bro-spinn/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/brospinn/SpinnKlient.kt
- bro-spinn/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/brospinn/SpinnService.kt
- bro-spinn/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/brospinn/EksternInntektsmeldingLoeserTest.kt
- bro-spinn/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/brospinn/HentEksternImRiverTest.kt
- bro-spinn/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/brospinn/SpinnKlientTest.kt
- bro-spinn/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/brospinn/SpinnServiceTest.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/rapidsrivers/service/ServiceRiver.kt
- felles/src/test/kotlin/no/nav/helsearbeidsgiver/felles/rapidsrivers/service/ServiceRiverTest.kt
- forespoersel-besvart/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/forespoerselbesvart/ForespoerselBesvartLoeser.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/EksternInntektsmeldingLagretIT.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/ForespoerselBesvartIT.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/utils/EndToEndTest.kt
Denne bruker fremdeles Redis under bordet, men på en måte som gjør at det ikke kan time ut, som er den største svakheten til de statefulle servicene. Etter denne endringen så skal jeg se på en versjon 2 uten Redis.
> Gjør SpinnService stateless

- .github/workflows/test.yml
- build.gradle.kts
- gradle.properties
Kotlins daemon går tom for minne når testene kjøres i parallell. Å fjerne parallell kjøringer fikser problemet. Det gjør også å øke minnet til Gradle sin daemon (hvis instillinger [Kotlins daemon arver fra](https://kotlinlang.org/docs/gradle-compilation-and-caches.html#gradle-daemon-arguments-inheritance)). Jeg gikk for sistnevnte.
> Bump Kotlin til 2.0.0

- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/json/KotlinxUtils.kt
- felles/src/test/kotlin/no/nav/helsearbeidsgiver/felles/json/KotlinxUtilsKtTest.kt
Det vil oppstå en feil under lesing av melding når en river leser meldinger fra rapid som ikke er de meldingene som riveren bryr seg om. For vårt system er det ikke kritisk at gjøre dette steget billigere, men det er jo fint med noe som er billig enn dyrt 😄
> Senk kostnad for feil under lesing fra melding

- .github/workflows/gradle-dependabot.yml
Jeg ødela den eksisterende workflowen med noen endringer til build-filen. Da jeg skulle lese litt på hvordan workflowen fungerte så kom jeg over en annen workflow-action som var anbefalt over den vi hadde: https://github.com/gradle/actions/blob/main/docs/setup-gradle.md#github-dependency-graph-support
> Erstatt workflow-action for dependency submission

- innsending/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/innsending/MapInntektsmelding.kt
- innsending/src/test/kotlin/no.nav.helsearbeidsgiver.inntektsmelding.innsending/MapInntektsmeldingKtTest.kt
Dette løser et problem der sykmeldt har flere AG og sykmeldinger som overlapper hull hos ulike AG. Gjelder kun når det bare etterspørs refusjon. Da bør vi ikke velge bestemmende fraværsdag ut i fra Spleis sine forslag, men heller regne ut selv.
> Beregn bestemmende fraværsdag dersom kun refusjon etterspørs

- api/build.gradle.kts
- api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/App.kt
- api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/RedisPoller.kt
- api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/aktiveorgnr/AktiveOrgnrRoute.kt
- api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/auth/Tilgangskontroll.kt
- api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/hentforespoersel/TrengerRoute.kt
- api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/hentselvbestemtim/HentSelvbestemtImRoute.kt
- api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/innsending/InnsendingRoute.kt
- api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/inntekt/InntektRoute.kt
- api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/inntektselvbestemt/InntektSelvbestemtRoute.kt
- api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/kvittering/KvitteringRoute.kt
- api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/lagreselvbestemtim/LagreSelvbestemtImRoute.kt
- api/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/RedisPollerTest.kt
- api/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/aktiveorgnr/AktiveOrgnrRouteKtTest.kt
- api/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/hentforespoersel/HentForespoerselRouteKtTest.kt
- api/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/hentforespoersel/TrengerRouteKtTest.kt
- api/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/hentselvbestemtim/HentSelvbestemtImRouteKtTest.kt
- api/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/innsending/InnsendingRouteKtTest.kt
- api/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/inntektselvbestemt/InntektSelvbestemtRouteKtTest.kt
- api/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/kvittering/KvitteringRouteKtTest.kt
- api/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/lagreselvbestemtim/LagreSelvbestemtImRouteKtTest.kt
- api/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/utils/TestUtils.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/ResultJson.kt
- innsending/build.gradle.kts
Gjør at redis polleren leser fra korrekt adresse i fremtiden, når bakoverkompatilitet fjernes fra ny redis store.
> Bruk ny redis store i redis poller

- api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/innsending/InnsendingRoute.kt
- innsending/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/innsending/InnsendingService.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/InnsendingIT.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/InnsendingServiceIT.kt
Det var to feil som fikses her, men begge stammer fra at vi gjør det nye skjemaet om til det gamle i backenden. Det gjør vi midlertidig for å støtte både ny og gammel kontrakt mot frontend, for bakoverkompatibilitet.
Når vi konverterer til gammelt format så blir fnr og orgnr satt til tomme strenger fordi det nye skjemaet ikke inkluderer disse feltene. Den første feilen var at valideringen trynte for disse tomme feltene. Etter at det var fikset så åpenbarte den andre feilen seg, som var at de tomme feltene ble sendt videre til `InnsendingService`, som med rette slo seg vrang. Denne måtte endres til å lese verdiene fra forespørselen (som den allerede delvis gjorde, men ikke i starten).
> Nytt skjema: Bruk orgnr og fnr fra forespørsel

- api/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/inntekt/InntektProducerTest.kt
- api/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/inntektselvbestemt/InntektSelvbestemtProducerTest.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/rapidsrivers/RiverUtils.kt
Jeg vil bytte `Key.SKJAERINGSTIDSPUNKT` til `Key.INNTEKTSDATO`, og samtidig teste en måte å bytte nøkler på.
`publish` er en funksjon som brukes i hele Simba for å skrive meldinger til Kafka. Her kan vi kopiere fra gamle til nye nøkler, slik som her, slik at verdien er duplisert i begge nøklene. I neste steg kan vi da bytte alle de gamle nøklene til de nye, uten inflight-problemer og vi slipper å bytte en og en nøkkel.
Tanken er å endelig endre `Key.UUID` til noe fornuftig med denne metoden når den er testet.
> Kopier nøkkel til erstatning ved publisering

- felles/src/testFixtures/kotlin/no/nav/helsearbeidsgiver/felles/test/mock/MockForespoersel.kt
- felles/src/testFixtures/kotlin/no/nav/helsearbeidsgiver/felles/test/mock/MockInntektsmelding.kt
- innsending/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/innsending/InnsendingService.kt
- innsending/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/innsending/MapInntektsmelding.kt
- innsending/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/innsending/UtledBestemmendeFravaersdag.kt
- innsending/src/test/kotlin/no.nav.helsearbeidsgiver.inntektsmelding.innsending/ForespoerselUtils.kt
- innsending/src/test/kotlin/no.nav.helsearbeidsgiver.inntektsmelding.innsending/MapInntektsmeldingKtTest.kt
- innsending/src/test/kotlin/no.nav.helsearbeidsgiver.inntektsmelding.innsending/UtledBestemmendeFravaersdagKtTest.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/InnsendingIT.kt
Appen `im-api` har tatt i bruk ny skjemaklasse, og sender den til `InnsendingService`. Tar i bruk den nye klassen i sistnevnte, som forenkler mapping fra skjema til inntektsmelding.
Merk at man fremdeles sender inntektsmelding på gammelt format videre fra `InnsendingService`.
> Map ny skjemaklasse til inntektsmelding

- api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/App.kt
- api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/tilgangorgnr/TilgangOrgnrRoute.kt
- api/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/tilgangselvbestemt/TilgangOrgnrRouteKtTest.kt
Dette trengs i forbindelse med selvbestemtskjema-flyten for å sikre at innsender faktisk har tilgang til å hente opplysninger fra Flex for det gitte orgnummeret.
> Legg til endepunkt for å sjekke tilgang til orgnummer

- config/db/dev-gcp.yml
- config/db/prod-gcp.yml
- config/feil-behandler/dev-gcp.yml
- config/feil-behandler/prod-gcp.yml
- config/nais.yml
- config/notifikasjon/dev-gcp.yml
- config/notifikasjon/prod-gcp.yml
- feil-behandler/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/feilbehandler/river/FeilLytter.kt
- feil-behandler/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/feilbehandler/river/FeilLytterTest.kt
En svakhet i feillytter gjorde at det ble laget nye jobber heller enn å oppdatere eksisterende, i spesialtilfeller der flere steg / behov feilet i den samme simba-transaksjonen (Steg i Service).
I tillegg krever nais-konfig nå at dbTier settes eksplisitt, oppdatert dette for alle instanser.
> feillytter - støtte for transaksjoner som går over flere behov.

- db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/tabell/InntektsmeldingEntitet.kt
- db/src/main/resources/db/migration/V16__inntektsmelding_skjema.sql
Vi ønsker å splitte opp flyten for innsending av inntektsmeldinger i to steg, med lagring av skjema i steg 1 og beriking i steg 2 (se `Del opp innsending i et synkront og et asynkront steg` https://github.com/navikt/helsearbeidsgiver-inntektsmelding/pull/582).
For å gjøre testing av https://github.com/navikt/helsearbeidsgiver-inntektsmelding/pull/582 enklere i dev, så ønsker vi å ta inn databasemigreringen i main først.
> Legg til kolonne for å lagre im skjema

- api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/kvittering/KvitteringRoute.kt
- berik-inntektsmelding-service/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/berikinntektsmeldingservice/UtledBestemmendeFravaersdag.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/domene/Forespoersel.kt
- felles/src/test/kotlin/no/nav/helsearbeidsgiver/felles/ForespoerselTest.kt
- gradle.properties
**Bakgrunn**
Spleis inkluderer ikke lenger egenmeldingsperioder når de sender oss forslag til bestemmende fraværsdag gjennom inntektsmeldingforespørslene.
**Løsning**
1. Beregn bestemmende fraværsdag med utgangspunkt i _både_ sykmeldingsperioder og egenmeldingsperioder. Bruk den tidligste av den beregnede og den Spleis-foreslåtte datoen.
2. Det kom fram etter samtaler med frontend-teamet at feltet `bestemmendeFraværsdag` brukes på kvitteringssiden i frontend som om det er inntektsdato (disse kan være ulike ved flere arbeidsforhold). Dette gjorde at vi viste frem feil dato på kvitteringen. Inntil vi får gjort jobben med å bytte til nytt `v1.Inntektsmelding`-objekt er en workaround at vi gir frontend inntektsdatoen på dette feltet dersom den eksisterer.
> Inkluder egenmeldinger ved beregning av bestemmende fraværsdag og inntektsdato

- gradle.properties
0.1.3 innførte vedtaksperiodeID i InntektsmeldingV1-formatet, som oversettes fra selvbestemt-payload. 
Selvbestemt payloaden har ikke vedtaksperiodeID satt i allerede innsendte (eller de nye, inntil dette kommer fra frontend), så deserialisering fra database leder til MissingFieldException. 
Versjon 0.1.4 setter vedtaksperiodeID til defaultverdi null i v1.Inntektsmelding
> bump hag-domene til 0.1.4 - setter vedtaksperiode til default null

- api/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/lagreselvbestemtim/LagreSelvbestemtImRouteKtTest.kt
- gradle.properties
Det viste seg at uten en defaultverdi for vedtaksperiodeId, så brakk vi innsendingen for selvbestemte IMer. Se https://github.com/navikt/hag-domene-inntektsmelding/pull/32
> Bump til nyeste domene for å gjøre selvbestemt innsending bakoverkompatibel

- berik-inntektsmelding-service/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/berikinntektsmeldingservice/BerikInntektsmeldingService.kt
**Bakgrunn**
Alle inntektsmeldinger blir registrert som `NY` på `årsakInnsending`. Grunnen er at vi overså at funksjonen som skal hente ut de nyeste eksisterende IMene finner skjemaet vi nettopp lagret i steget før, istedenfor å finne de tidligere innsendte IMene.
**Løsning**
Bruk `forespoersel.erBesvart` fra Storebror til å avgjøre `aarsakInnsending` i Berikservice.
> Bruk forespoersel.erBesvart til å avgjøre aarsakInnsending i berikservice

- berik-inntektsmelding-service/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/berikinntektsmeldingservice/BerikInntektsmeldingService.kt
**Bakgrunn**
Jeg og @mortenbyhring var litt usikre på om den praktiske forskjellen mellom utledningen av bestemmende fraværsdag og defaultverdien som settes når man bruker `.convert()` for å konvertere fra ny IM-dataklasse til gammel. Det viser seg (som mistenkt) at de ikke alltid er like, og at den utledede gir den mest presise verdien (tar hensyn til agp og egenmeldingsdager).
**Løsning**
Fjern ekstra logging.
> Rens vekk logging av bestemmende fraværsdag som vi ikke trenger lenger

- berik-inntektsmelding-service/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/berikinntektsmeldingservice/BerikInntektsmeldingService.kt
- berik-inntektsmelding-service/src/test/kotlin/no.nav.helsearbeidsgiver.inntektsmelding.berikinntektsmeldingservice/BerikInntektsmeldingServiceTest.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/rapidsrivers/service/Service.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/BerikInntektsmeldingServiceIT.kt
**Bakgrunn**
Etter endringen i https://github.com/navikt/helsearbeidsgiver-inntektsmelding/pull/677 så trenger vi ikke lenger hente lagrede IMer i beriktjenesten. Dette er fordi vi nå bruker `forespoersel.erBesvart` fra Storebror til å avgjøre `aarsakInnsending` istedenfor lagrede IMer.
**Løsning**
Fjern steget i BerikInntektsmeldingService som henter lagrede IMer. Siden dette skjedde i `steg2`, så forskyver rekken av steg seg ett hakk fremover og vi vil ikke lenger ha `steg5`. (`Steg5` blir `steg4`, `steg4` blir `steg3`, `steg3` blir `steg2`. `Steg0` og `steg1` forblir uendret)
> Slutt å hente lagrede IMer i Beriktjenesten

- berik-inntektsmelding-service/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/berikinntektsmeldingservice/BerikInntektsmeldingService.kt
Jeg ønsker å bytte `Key.INNTEKTSMELDING` med `Key.INNTEKTSMELDING_DOKUMENT`, for å kunne bruke førstnevnte til `InntektsmeldingV1` i et senere steg. De fleste andre steder har det samme forholdet mellom gammel og ny nøkkel og IM-klasse.
> Klargjør bytte av feltnøkkel

- berik-inntektsmelding-service/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/berikinntektsmeldingservice/BerikInntektsmeldingService.kt
- berik-inntektsmelding-service/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/berikinntektsmeldingservice/UtledBestemmendeFravaersdag.kt
- berik-inntektsmelding-service/src/test/kotlin/no.nav.helsearbeidsgiver.inntektsmelding.berikinntektsmeldingservice/BerikInntektsmeldingServiceTest.kt
- db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/river/LagreImRiver.kt
- db/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/river/LagreImRiverTest.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/BerikInntektsmeldingServiceIT.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/InnsendingIT.kt
Bytter feltnøkkel for å senere kunne bruke `Key.INNTEKTSMELDING` til å sende `InntektsmeldingV1`.
> Bytt feltnøkkel for inntektsmelding

- berik-inntektsmelding-service/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/berikinntektsmeldingservice/BerikInntektsmeldingService.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/Key.kt
- joark/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/JournalfoerImRiver.kt
- joark/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/JournalfoerImRiverTest.kt
Vi ønsker å bruke ny IM-klasse. Her sender vi gammel og ny klasse til journalføringsappen, så prøver den å bruke ny klasse, men faller tilbake til gammel dersom den nye mangler. Dette gjør vi i en kort overgangsperiode, for å forhindre in-flight problemer.
> Send ny IM-klasse til journalføringsapp

- joark/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/dokument/PdfDokument.kt
Vi burde bruke inntektsdato istedenfor bestemmende fraværsdag fordi det er fra den dagen vi henter inntekt. Disse to er kun forskjellige ved flere AG-er.
> Bruk inntektsdato i PDF

- db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/InntektsmeldingRepository.kt
- db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/river/LagreImSkjemaRiver.kt
- db/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/RepositoryTest.kt
- db/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/river/LagreImSkjemaRiverTest.kt
- innsending/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/innsending/InnsendingService.kt
- innsending/src/test/kotlin/no.nav.helsearbeidsgiver.inntektsmelding.innsending/InnsendingServiceTest.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/BerikInntektsmeldingServiceIT.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/InnsendingIT.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/InnsendingServiceIT.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/KvitteringIT.kt
Forespørsel-ID ligger i skjema, så det er ikke nødvending å sende som eget felt.
> Fjern unødvendig meldingsfelt fra river som lagrer skjema

- db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/SelvbestemtImRepo.kt
- db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/river/LagreJournalpostIdRiver.kt
- db/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/SelvbestemtImRepoTest.kt
- db/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/TestData.kt
- db/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/river/LagreJournalpostIdRiverTest.kt
- distribusjon/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/distribusjon/DistribusjonRiverTest.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/InnsendingIT.kt
Vi ønsker å bruke ny IM-klasse overalt. Nå er det lagring av journalpost-ID sin tur.
> Bruk ny IM-klasse under lagring av journalpost-ID

- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/AktiveOrgnrServiceIT.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/BerikInntektsmeldingServiceIT.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/ForespoerselBesvartIT.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/InnsendingIT.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/InnsendingServiceIT.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/InntektSelvbestemtIT.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/KvitteringIT.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/LagreSelvbestemtIT.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/NotifikasjonIT.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/TilgangskontrollIT.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/utils/Messages.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/utils/MessagesTest.kt
Nested data har blitt normen, så da endrer vi noen defaultverdier i integrasjonstestene.
> Integrasjonstest: Bruk nested data som default i meldingsfiltrering

- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/domene/Forespoersel.kt
- felles/src/test/kotlin/no/nav/helsearbeidsgiver/felles/ForespoerselTest.kt
Spleis har sluttet å hensynta egenmeldinger når de utleder forslag til bestemmende fraværsdag (BF). Derfor har vi lagt til kode for å vurdere om egenmeldinger endrer forslaget, og heller utlede BF selv. Fordi Spleis sitter på mer info enn oss så vil vi bruke forslagene deres der vi kan, som når det ikke finnes noen egenmeldinger.
> Bestemmende fraværsdag: Bruk forslag dersom egenmeldinger er tom

- api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/App.kt
- api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/HelsesjekkerRouting.kt
- api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/hentforespoersel/HentForespoerselRoute.kt
- api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/hentforespoerselIdListe/HentForespoerselIdListeRoute.kt
- api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/innsending/InnsendingRoute.kt
- api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/kvittering/KvitteringRoute.kt
- api/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/utils/TestUtils.kt
- db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/ForespoerselRepository.kt
- db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/InntektsmeldingRepository.kt
- felles/build.gradle.kts
- felles/gradle.properties
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/metrics/Metrics.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/utils/EndToEndTest.kt
- pdl/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/pdl/HentPersonerRiverTest.kt
Flytter alle metrikkdefinisjoner i egen fil for å få bedre oversikt.
Fjerner også `CollectorRegistry.defaultRegistry.clear()` fra et par tester, inkludert integrasjonstestene. Uten denne skal visstnok testene erfart problemer før, men de viser ingen tegn til det nå. Teorien er at noe har endret seg i RR-biblioteket.
> Flytt alle metrikkdefinisjoner til egen fil

- innsending/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/innsending/App.kt
- innsending/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/innsending/InnsendingService.kt
- innsending/src/test/kotlin/no.nav.helsearbeidsgiver.inntektsmelding.innsending/InnsendingServiceTest.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/InnsendingIT.kt
Siden `InnsendingService` legger dataen den trenger videre på data-nøkkelen i meldingene og ikke har noen parallelle operasjoner, så trenger den ikke lenger hjelp fra Redis til å huske hva som foregår.
> Gjør InnsendingService stateless

- config/nais.yml
Man trenger ikke denne, ref. femte paragraf i https://doc.nav.cloud.nais.io/workloads/explanations/good-practices/?h=limits#set-reasonable-resource-requests-and-limits.
> Fjern unødvendig CPU-begrensning

- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/Key.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/rapidsrivers/pritopic/Pri.kt
- forespoersel-mottatt/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/forespoerselmottatt/ForespoerselMottattRiver.kt
- forespoersel-mottatt/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/forespoerselmottatt/ForespoerselMottattRiverTest.kt
- gradle.properties
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/ForespoerselMottattIT.kt
- notifikasjon/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/HentDataTilSakOgOppgaveService.kt
- notifikasjon/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/HentDataTilSakOgOppgaveServiceTest.kt
Forespørsler av typen `begrenset` skal ikke ha påminnelser, og siden Simba ikke har noe forhold til `komplett`/`begrenset` må vi få denne informasjonen fra Storebror.
Henger sammen med https://github.com/navikt/helsearbeidsgiver-bro-sykepenger/pull/80, som må prodsettes først.
> Ta i mot nytt felt fra Storebror for å avgjøre om oppgaver skal ha påminnelser

- notifikasjon/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/ArbeidsgiverNotifikasjonKlientUtils.kt
- notifikasjon/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/ArbeidsgiverNotifikasjonKlientUtilsTest.kt
Fødselsdatoen må endres for d-nummer, som bruker +4 på første siffer i fødselsdatostrengen: https://www.skatteetaten.no/person/folkeregister/identitetsnummer/d-nummer/
> Støtt d-nummer i saktittel

- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/Key.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/domene/ForespoerselFraBro.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/rapidsrivers/pritopic/Pri.kt
- forespoersel-mottatt/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/forespoerselmottatt/ForespoerselMottattRiver.kt
- forespoersel-mottatt/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/forespoerselmottatt/ForespoerselMottattRiverTest.kt
- helsebro/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/helsebro/domene/ForespoerselListeSvar.kt
- helsebro/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/helsebro/domene/ForespoerselSvar.kt
- helsebro/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/helsebro/MockUtils.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/BerikInntektsmeldingServiceIT.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/ForespoerselMottattIT.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/InnsendingIT.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/InnsendingServiceIT.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/mock/MockData.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/utils/EndToEndTest.kt
For å kunne ta med sykepemeldingsperioder i varselet til arbeidsgiver trenger i å videresende hele forespørselen i forespørsel mottatt eventet. Dette kan også brukes i lps-apiet.
> videresend  hele forespørselen i forespoerselMottatt eventet

- notifikasjon/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/HentDataTilSakOgOppgaveService.kt
- notifikasjon/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/river/OpprettForespoerselSakOgOppgaveRiver.kt
- notifikasjon/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/river/OpprettForespoerselSakOgOppgaveRiverTest.kt
Forespoersel var nullable for å unngå innflight problemer ved prodsetting. Det er ikke nødvendig lenger
> Forespoersel ikke nullable ved opprettelse av sak og oppgave

- db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/river/LagreEksternImRiver.kt
- db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/river/LagreJournalpostIdRiver.kt
- db/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/river/LagreEksternImRiverTest.kt
- db/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/river/LagreJournalpostIdRiverTest.kt
- distribusjon/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/distribusjon/DistribusjonRiverTest.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/InnsendingIT.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/LagreSelvbestemtIT.kt
Bytter til en event som er mer presis. Neste ledd i kjeden (distribusjon) forventer allerede den nye eventen.
> Bruk ny event for journalpost ID lagret

- distribusjon/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/distribusjon/DistribusjonRiver.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/InnsendingIT.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/LagreSelvbestemtIT.kt
- joark/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/JournalfoerImRiver.kt
- joark/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/JournalfoerImRiverTest.kt
Journalføring får en egen (resirkulert) event for å komme oss bort fra behov i den asykrone flyten.
> Bruk egen event for fullført journalføring

- db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/river/LagreJournalpostIdRiver.kt
- db/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/river/LagreJournalpostIdRiverTest.kt
- feil-behandler/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/feilbehandler/river/FeilLytter.kt
- feil-behandler/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/feilbehandler/river/FeilLytterTest.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/EventTypes.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/InnsendingIT.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/LagreSelvbestemtIT.kt
- joark/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/JournalfoerImRiver.kt
- joark/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/JournalfoerImRiverTest.kt
Behov er ikke nødvendig i den asynkrone flyten (unntatt i servicer).
> Fjern unødvendig behov brukt under lagring av journalpost-ID

- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/domene/Forespoersel.kt
- felles/src/test/kotlin/no/nav/helsearbeidsgiver/felles/ForespoerselTest.kt
Sykmeldt kan rapportere egenmeldinger som ikke er gyldige dersom det ikke inngår i en AGP. Spleis sender oss egenmeldinger uansett, så vi ønsker å ignorere egenmeldinger dersom Spleis ikke har bedt om AGP.
> Bestemmende fraværsdag: Ignorer egenmeldinger om AGP ikke er påkrevd

- notifikasjon/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/ArbeidsgiverNotifikasjonKlientUtils.kt
- notifikasjon/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/river/OpprettForespoerselSakOgOppgaveRiverTest.kt
Endrer litt på formuleringer i epost/sms-varselet og påminnelsen for oppgaven.
- Sykmeldingsperioder i varselet.
- Tankestrek i påminnelsetittel.
- orgnr blir org.nr. (https://sprakradet.no/spraksporsmal-og-svar/forkorting-av-organisasjonsnummer-fodselsnummer-og-personnummer/)
> Juster tittel og innhold i oppgavevarsel og påminnelse

- notifikasjon/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/ArbeidsgiverNotifikasjonKlientUtils.kt
Den korrekte forkortelsen (`org.nr.`) blir en lenke i epostvarselet. Endrer derfor tilbake til `orgnr`.
> Endre orgnr-format i varseltekst 

- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/HentForespoerselIT.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/utils/EndToEndTest.kt
- notifikasjon/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/river/UtgaattForespoerselRiver.kt
- notifikasjon/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/river/UtgaattForespoerselRiverTest.kt
Alle forespølser som blir forkastet vil i dag få sak og oppgave satt til utgått, men gamle forkastede forespørsler vil ikke det. Denne endringen gjør at gamle forkastede forespørsler får sak og oppgave satt til utgått dersom noen forsøker å hente dem. Slik vil man forhåpentligvis hjelpe noen arbeidsgivere å forstå at forespørselen de prøver å finne ikke lenger trenger en IM.
> Sett ikke funnet forespørsel til utgått

- bro-spinn/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/brospinn/SpinnService.kt
- bro-spinn/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/brospinn/SpinnServiceTest.kt
Noen selvbestemte IM-er kan matche forespørsler og dermed lagres som en ekstern besvarelse av forespørsel. Legger inn et unntak for disse, på samme måte som forespurte IM-er sendt inn på nav.no.
> Ikke lagre selvbestemt IM som ekstern IM

- berik-inntektsmelding-service/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/berikinntektsmeldingservice/BerikInntektsmeldingService.kt
- berik-inntektsmelding-service/src/test/kotlin/no.nav.helsearbeidsgiver.inntektsmelding.berikinntektsmeldingservice/BerikInntektsmeldingServiceTest.kt
- db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/river/LagreEksternImRiver.kt
- innsending/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/innsending/KvitteringService.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/BerikInntektsmeldingServiceIT.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/InnsendingIT.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/LagreSelvbestemtIT.kt
- joark/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/JournalfoerImRiver.kt
- selvbestemt-lagre-im-service/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/selvbestemtlagreimservice/LagreSelvbestemtImService.kt
- selvbestemt-lagre-im-service/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/selvbestemtlagreimservice/LagreSelvbestemtImServiceTest.kt
Et forsøk på å være mer konsekvent i å sende datafelter under Key.DATA.
> Send data som nested objekt ved mottatt IM

- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/Key.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/rapidsrivers/RiverUtils.kt
Dette er innsats for å strømlinjeforme formatet på meldingsnøklene våre, der vi i gamle dager kjørte en "gjør hva du vil"-policy.
Skal benytte anledningen til å endre `Key.UUID` også, i egen PR. Lar derfor testene som ble endret i https://github.com/navikt/helsearbeidsgiver-inntektsmelding/pull/772 forbli inntil videre.
> Erstatt key i melding for forespoersel-ID

- config/notifikasjon/dev-gcp.yml
- config/notifikasjon/prod-gcp.yml
**Bakgrunn**
Eksperimentet vårt for å teste effekten av påminnelser viser en klar økning av innsendte inntektsmeldinger for gruppen vi sendte påminnelser til sammenliknet med kontrollgruppen. Vi ønsker derfor å skru på påminnelser til alle.
**Løsning**
Skru på påminnelser på oppgaver i prod (28 dager etter oppgaveopprettelse) og dev (10 minutter etter oppgaveopprettelse).
> Skru på påminnelse etter 28 dager for alle

- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/Key.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/rapidsrivers/RiverUtils.kt
Ønsker å bytte `Key.UUID` med den mer meningsbærende `Key.KONTEKST_ID`. Valgte "kontekst-ID" siden verdien identifiserer konteksten meldingene befinner seg i, i forhold til de andre meldingene og for hvilken bruker man utfører handlingen (som meldingen beskriver) for.
> Legg til erstatningskey i melding for kontekst-ID (kalt 'uuid')

- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/Key.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/rapidsrivers/RiverUtils.kt
Ut med gammel nøkkel og inn med ny.
Endrer enum-navnet i en egen PR, så disse funksjonelle endringene ikke drukner i masse renaming.
> Erstatt key i melding for kontekst-ID (kalt 'uuid')

- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/rapidsrivers/redis/RedisStore.kt
- felles/src/test/kotlin/no/nav/helsearbeidsgiver/felles/rapidsrivers/redis/RedisStoreTest.kt
- trengerservice/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/trengerservice/HentForespoerselService.kt
Denne endringen gjør at skriving og lesing av feil under henting av verdier ligner mer på skriving og lesing av suksessfullt hentede verdier. Da blir flyten under feil lettere å følge.
> Skriv feil til Redis per key

- api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/HelsesjekkerRouting.kt
- config/nais.yml
Dette er et forsøk på å fikse prodsettingsproblemene våre. Nå skal podene få 2 minutter (10 + 5 * 22 sek) på å starte. Denne grensen er basert på gjetning, så den kan alltids justeres. Det er uansett bare en maksgrense. Startup proben sier seg ferdig så snart den får svar.
https://doc.nav.cloud.nais.io/workloads/application/reference/application-spec/#startup
> Tillat podene mer tid på startup ved deploy

- aktiveorgnrservice/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/aktiveorgnrservice/AktiveOrgnrService.kt
- berik-inntektsmelding-service/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/berikinntektsmeldingservice/BerikInntektsmeldingService.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/rapidsrivers/RiverUtils.kt
- felles/src/test/kotlin/no/nav/helsearbeidsgiver/felles/rapidsrivers/RiverUtilsKtTest.kt
- innsending/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/innsending/InnsendingService.kt
- innsending/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/innsending/KvitteringService.kt
- inntekt-selvbestemt-service/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/inntektselvbestemtservice/InntektSelvbestemtService.kt
- inntektservice/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/inntektservice/InntektService.kt
- notifikasjon/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/HentDataTilPaaminnelseService.kt
- notifikasjon/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/HentDataTilSakOgOppgaveService.kt
- selvbestemt-hent-im-service/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/selvbestemthentimservice/HentSelvbestemtImService.kt
- selvbestemt-lagre-im-service/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/selvbestemtlagreimservice/LagreSelvbestemtImService.kt
- tilgangservice/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/tilgangservice/TilgangForespoerselService.kt
- tilgangservice/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/tilgangservice/TilgangOrgService.kt
- trengerservice/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/trengerservice/HentForespoerselService.kt
- trengerservice/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/trengerservice/HentForespoerslerForVedtaksperiodeIdListeService.kt
Dette er nødvendig for å sikre oss at meldingene på Kafka blir lest i samme rekkefølge som de blir skrevet.
> Publiser meldinger med Kafka-key i servicer

- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/Key.kt
- forespoersel-besvart/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/forespoerselbesvart/ForespoerselBesvartRiver.kt
- forespoersel-besvart/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/forespoerselbesvart/ForespoerselBesvartRiverTest.kt
Siste nøkkel med feil formattering 🥳
> Slettet midlertidlig spinn im id key

- api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/hentforespoersel/HentForespoerselProducer.kt
- api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/hentforespoerselIdListe/HentForespoerslerProducer.kt
- feil-behandler/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/feilbehandler/river/FeilLytter.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/Key.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/rapidsrivers/pritopic/Pri.kt
- felles/src/test/kotlin/no/nav/helsearbeidsgiver/felles/json/KotlinxUtilsKtTest.kt
- forespoersel-mottatt/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/forespoerselmottatt/ForespoerselMottattRiver.kt
- forespoersel-mottatt/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/forespoerselmottatt/ForespoerselMottattRiverTest.kt
- helsebro/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/helsebro/ForespoerselSvarRiver.kt
- helsebro/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/helsebro/VedtaksperiodeIdForespoerselSvarRiver.kt
- helsebro/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/helsebro/ForespoerselSvarRiverTest.kt
- helsebro/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/helsebro/MockUtils.kt
- helsebro/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/helsebro/VedtaksperiodeIdForespoerselSvarRiverTest.kt
- inntektservice/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/inntektservice/InntektServiceTest.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/utils/EndToEndTest.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/utils/MessagesTest.kt
- tilgangservice/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/inntektservice/TilgangForespoerselServiceTest.kt
- tilgangservice/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/inntektservice/TilgangOrgServiceTest.kt
Med strengene så hadde vi en slags dobbel definisjon. Nå som vi sammenstilt strengverdi med enumnavn de fleste tilfellene, så kan vi kvitte oss med den unødvendige strengen.
> Fjern overflødig strengverdi i enum for json-nøkler

- api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/hentforespoersel/HentForespoerselResponse.kt
- api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/hentforespoersel/HentForespoerselRoute.kt
- api/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/hentforespoersel/HentForespoerselRouteKtTest.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/domene/Forespoersel.kt
- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/domene/ForespoerselFraBro.kt
- felles/src/testFixtures/kotlin/no/nav/helsearbeidsgiver/felles/test/mock/MockForespoersel.kt
- forespoersel-mottatt/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/forespoerselmottatt/ForespoerselMottattRiverTest.kt
- helsebro/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/helsebro/MockUtils.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/BerikInntektsmeldingServiceIT.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/ForespoerselMottattIT.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/InnsendingIT.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/InnsendingServiceIT.kt
- integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/mock/MockData.kt
**Forklaring av variabel:**
Denne datoen er tidspunktet forespørselen i helsebro ble opprettet, men kan være et tilfeldig tidspunkt etter opprettelse.
For flexjar usecase kan vi for eksempel garantere at forespørselen har en alder av 28 eller mer dager.
________
**Testing av funksjonalitet:**
✅ Testet opprettelse av IM i dev miljø
✅ Funnet endring i API: `"opprettetUpresisIkkeBruk": "2024-12-04",`
✅ Funnet endring i dev logs for im-api: `"opprettetUpresisIkkeBruk":"2024-12-04"`
> Legg til upresis opprettet dato

- felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/rapidsrivers/service/Service.kt
Vi ønsker å logge mer slik at vi kan bedre forstå situasjonene hvor dette skjer.
> Logg melding som mangler startdata for service

- .github/workflows/prod.yml
Jeg misforsto noe dokumentasjon. Vi bruker tags i prodsetting, men tags blir ikke hentet fra repoet i Github Actions. Denne endringen må med for at prod workflowen skal fungere som tiltenkt.
> Fiks henting av tags i prod workflow

- .github/workflows/prod.yml
Et nytt forsøk på å fikse prod workflow. Siste feil skyldes at `fetch-tags: true` ikke fungerer med en workflow som trigges av en tag, slik vår gjør.
Se https://github.com/navikt/helsearbeidsgiver-inntektsmelding/actions/runs/12235255860/job/34126166060#step:2:58 for feilende workflow.
Se https://github.com/actions/checkout/issues/1467 for Github issue for `checkout`-actionen.
> Fiks henting av tags i prod workflow (v2)

- aareg/gradle.properties
- altinn/gradle.properties
- bro-spinn/gradle.properties
- brreg/gradle.properties
- gradle.properties
- inntekt/gradle.properties
- integrasjonstest/build.gradle.kts
- integrasjonstest/gradle.properties
- joark/gradle.properties
- notifikasjon/gradle.properties
- pdl/gradle.properties
Klientavhengigheten ble i sin tid lagt til filen med fellesavhengigheter for integrasjonstestene trengte dem. Det løser vi her ved å la integrasjonstestene lese avhengighetsfilene til alle appene.
En bonus med dette er at når vi flytter dem ut av fellesfilen så trenger vi ikke lenger å prodsette alle appene dersom vi oppdaterer en enkelt klient. Det gjør vi i dag fordi endringer i fellesfilen skal i utgangspunktet påvirke hver eneste app.
> Definér klientavhengighetene i appene de brukes i

- apps/berik-inntektsmelding-service/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/berikinntektsmeldingservice/BerikInntektsmeldingService.kt
- apps/db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/river/LagreImRiver.kt
- apps/db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/river/LagreJournalpostIdRiver.kt
- apps/db/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/river/LagreImRiverTest.kt
- apps/db/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/river/LagreJournalpostIdRiverTest.kt
- apps/distribusjon/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/distribusjon/DistribusjonRiver.kt
- apps/distribusjon/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/distribusjon/DistribusjonRiverTest.kt
- apps/joark/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/JournalfoerImRiver.kt
- apps/joark/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/TilDokumenter.kt
- apps/joark/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/TilXmlInntektsmelding.kt
- apps/joark/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/dokument/XMLUtils.kt
- apps/joark/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/JournalfoerImRiverTest.kt
- apps/joark/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/TilDokumenterKtTest.kt
- apps/joark/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/TilXmlInntektsmeldingTest.kt
- apps/joark/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/dokument/XMLMapperTest.kt
Spleis bruker ikke lenger denne datoen, så da kan vi fjerne den. Gjør det i to deler for å unngå problemer med in-flight meldinger.
> Fjern bestemmenede fraværsdag (del 1)

- apps/integrasjonstest/build.gradle.kts
- apps/tilgangservice/build.gradle.kts
Disse ble gjort overflødige i https://github.com/navikt/helsearbeidsgiver-inntektsmelding/commit/56a2f4e69ac90b2598312b571eb0ed5ba5a90871#diff-5625e3601fa0ad3a6a2824239e5a2fde71c149597d31394f9224a08c24be7b9dL6.
> Fjern ubrukte build-filer

- apps/feil-behandler/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/feilbehandler/App.kt
- apps/feil-behandler/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/feilbehandler/prosessor/FeilProsessor.kt
- apps/feil-behandler/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/feilbehandler/river/FeilLytter.kt
- apps/feil-behandler/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/feilbehandler/river/FeilLytterTest.kt
Skriver denne om til ObjectRiver for å få mer utfyllende logging og en feilhåndtering som favner litt bredere. Da slipper vi også å endre mer når vi oppdaterer til en nyere versjon av R&R.
> Bruk ObjectRiver i FeilLytter

- apps/integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/utils/ContainerTest.kt
Siste annonserte oppdatering, så vidt jeg kan se: https://nav-it.slack.com/archives/C01DE3M9YBV/p1724826006909269?thread_ts=1724222746.503759&cid=C01DE3M9YBV
Sammenheng mellom Confluent- og Kafka-versjon: https://docs.confluent.io/platform/current/installation/versions-interoperability.html#cp-and-apache-ak-compatibility
> Integrasjonstest: Bruk Kafka-versjon som ligner prod

- .github/workflows/build.yml
- .github/workflows/gradle-dependabot.yml
- .github/workflows/integrasjonstest.yml
- .github/workflows/prod.yml
- .github/workflows/test.yml
Bumper `setup-gradle` fra v3 til v4. Det medfører at caching via `actions/cache` og/eller `with.cache: gradle` fra `actions/setup-java` fjernes, som beskrevet [her](https://github.com/gradle/actions/blob/main/docs/setup-gradle.md#incompatibility-with-other-caching-mechanisms).
Bumper `dependency-submission` fra v3 til v4.
> Oppdater gradle-actions i workflows

- apps/aareg/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/aareg/HentArbeidsforholdRiver.kt
- apps/aareg/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/inntekt/HentArbeidsforholdRiverTest.kt
- apps/altinn/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/altinn/AltinnRiver.kt
- apps/altinn/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/altinn/Mock.kt
- apps/brreg/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/brreg/HentVirksomhetNavnRiver.kt
- apps/brreg/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/brreg/HentVirksomhetNavnRiverTest.kt
- apps/db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/river/HentLagretImRiver.kt
- apps/db/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/river/HentLagretImRiverTest.kt
- apps/felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/rapidsrivers/RiverUtils.kt
- apps/felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/rapidsrivers/river/ObjectRiver.kt
- apps/felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/rapidsrivers/river/OpenRiver.kt
- apps/felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/rapidsrivers/river/PriObjectRiver.kt
- apps/felles/src/test/kotlin/no/nav/helsearbeidsgiver/felles/rapidsrivers/RiverUtilsKtTest.kt
- apps/inntekt/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/inntekt/HentInntektRiver.kt
- apps/inntekt/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/inntekt/HentInntektRiverTest.kt
- apps/pdl/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/pdl/HentPersonerRiver.kt
- apps/pdl/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/pdl/HentPersonerRiverTest.kt
Utvalgte rivers får tilsendt hvilken nøkkel de skal bruke når de publiserer en svarmelding. Disse nøklene blir alltid sendt i dag. Denne endringen gjør at nøklene går fra å være valgfri til påkrevd i riverne som mottar dem.
> Krev tilsendt svarnøkkel i utvalgte rivers

- apps/db/build.gradle.kts
- apps/feil-behandler/build.gradle.kts
- config/nais.yml
Enabler flagget i både dev og prod pga litt tuklete konfig. 
Det vil uansett også måtte enables manuelt av Nais-teamet i tillegg til disse flaggene, 
og det vil ikke være noe problem om det evt skrus på i dev også, uansett.
Måtte også touche noen filer i respektive apper, for å trigge deploy.
> Enabler auditlog på databaser

- apps/joark/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/TilDokumenter.kt
- apps/joark/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/TilDokumenterKtTest.kt
Testet i `https://gosys-q1.dev.intern.nav.no/gosys/bruker/brukeroversikt.jsf` at dokumentbeskrivelse er endret.  
`Saksid : 187032903`
> fjernet orgnr fra dokarkiv dokument tittel

- apps/api/build.gradle.kts
- apps/api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/innsending/InnsendingRoute.kt
- apps/api/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/hentselvbestemtim/HentSelvbestemtImRouteKtTest.kt
- apps/felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/utils/EndringsAarsakUtils.kt
- apps/felles/src/testFixtures/kotlin/no/nav/helsearbeidsgiver/felles/test/mock/MockInntektsmelding.kt
- apps/joark/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/dokument/PdfDokument.kt
- apps/joark/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/dokument/PdfDokumentTest.kt
- gradle.properties
Lager en draft da det blir mye kode å se på om hele funksjonen skulle vært klar for prod.
Funksjonen `Flere begrunnelser` legger til støtte for flere inntekt endring begrunnelser (`List<endringsAarsak>`)
For å støtte dette i prod beholder vi den gamle verdien slik at frontend ikke må endres og vi unngår inflight errors.
**0:** I denen versjonen har jeg oppdatert IM modellen til `hagDomeneInntektsmeldingVersion=0.1.8-SNAPSHOT`
Denne beholder gamle endringsAarsak variabelen og legger til en nullable liste med deafult verdi `= null`
```kotlin
data class Inntekt(
val beloep: Double,
val inntektsdato: LocalDate,
val naturalytelser: List<Naturalytelse>,
val endringAarsak: InntektEndringAarsak?,
val endringAarsaker: List<InntektEndringAarsak>? = null, // <-- lagt til denne
) {
```
**1:** Listen …
> Flere begrunnelser v1 - Oppdatert IM modell og PDF støtte

- apps/felles/src/testFixtures/kotlin/no/nav/helsearbeidsgiver/felles/test/mock/MockInntektsmelding.kt
- gradle.properties
Valider refusjon endringsdatoer (må være etter AGP der vi har dette, ellers sjekkes det mot inntektDato) 
Valideringen er allerede implementert på frontend
https://trello.com/c/pckSBdXy/405-hindre-ag-fra-%C3%A5-sende-refusjonsendringer-og-opph%C3%B8r-som-er-f%C3%B8r-eller-under-agp
> strengere refusjonsendring dato-validering

- apps/joark/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/TilXmlInntektsmelding.kt
- apps/joark/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/TilXmlInntektsmeldingTest.kt
En forenklet løsnining for å unngå at endring blir nødvending i programvare som leser XML filen.
> Støtte flere endringsÅrsaker array i XML ved å ta første element

- apps/db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/InntektsmeldingRepository.kt
- apps/db/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/InntektsmeldingRepositoryTest.kt
- apps/felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/utils/EndringsAarsakUtils.kt
Inntekt endringsAarsaker array fylles om de ikke er definert i gamle dokumenter lagret i Simba databasen når de blir hentet.
> Flere inntekt begrunnelser fylles når IM hentes fra databasen

- apps/joark/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/dokument/PdfDokument.kt
- apps/joark/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/dokument/PdfDokumentTest.kt
I dagens løsning inkluderer PDFen denne teksten selv om ingen arbeidsgiverperiode er definert:
```
Betaler arbeidsgiver full lønn til arbeidstaker i arbeidsgiverperioden?
JA
```
Denne PR endringen inkluderer bare teksten om `arbeidsgiverperioder.isNotEmpty()`
> Tar bort urelevant felt om IM ikke har AGP

- apps/db/src/main/resources/db/migration/V19__inntektsmelding_add_im_id.sql
`UNIQUE` skal også sørge for at kolonnen blir indeksert, som vi trenger når vi skal oppdatere radene med journalpost-ID.
Sniker med kolonne for avsendernavn også, som nå lagres i IM på gammelt format.
> Legg til kolonne for inntektsmelding-ID i database

- apps/db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/InntektsmeldingRepository.kt
- apps/db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/domene/ConvertGammeltFormatUtils.kt
- apps/db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/domene/ConvertNyttFormatUtils.kt
- apps/db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/domene/FullLoennIAgpGammeltFormat.kt
- apps/db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/domene/InntektGammeltFormat.kt
- apps/db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/domene/InntektsmeldingGammeltFormat.kt
- apps/db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/domene/NaturalytelseGammeltFormat.kt
- apps/db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/domene/RefusjonGammeltFormat.kt
- apps/db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/river/LagreImRiver.kt
- apps/db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/tabell/InntektsmeldingEntitet.kt
- apps/db/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/InntektsmeldingRepositoryTest.kt
- apps/db/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/domene/ConvertTest.kt
- apps/db/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/river/LagreImRiverTest.kt
- apps/felles/src/testFixtures/kotlin/no/nav/helsearbeidsgiver/felles/test/mock/MockInntektsmelding.kt
- apps/integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/BerikInntektsmeldingServiceIT.kt
- apps/integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/InnsendingServiceIT.kt
- apps/integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/KvitteringIT.kt
Lagrer denne ID-en slik at vi kan bruke den i ettertid.
Sniker også med en del dataklasser og konverteringsfunksjoner, men disse er stort sett blåkopiert fra domenepakken. Disse klassene er nå kun brukt for å lese gamle databaserader, så de kan fjernes fra domenepakken etter denne PR-en.
> Lagre inntektsmelding-ID i database

- apps/berik-inntektsmelding-service/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/berikinntektsmeldingservice/BerikInntektsmeldingService.kt
- apps/db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/InntektsmeldingRepository.kt
- apps/db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/river/LagreImRiver.kt
- apps/db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/river/LagreImSkjemaRiver.kt
- apps/db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/river/LagreJournalpostIdRiver.kt
- apps/db/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/InntektsmeldingRepositoryTest.kt
- apps/db/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/river/LagreImRiverTest.kt
- apps/db/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/river/LagreJournalpostIdRiverTest.kt
- apps/felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/Key.kt
- apps/innsending/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/innsending/InnsendingService.kt
- apps/innsending/src/test/kotlin/no.nav.helsearbeidsgiver.inntektsmelding.innsending/InnsendingServiceTest.kt
- apps/integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/BerikInntektsmeldingServiceIT.kt
- apps/integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/InnsendingServiceIT.kt
- apps/integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/KvitteringIT.kt
Nå som inntektsmelding-ID finnes i databasen så kan den brukes til å sette journalpost-ID på korrekt rad, og innsending-ID kan fases ut. Sistnevnte må gjøres i flere steg, for å unngå in-flight problemer.
> Bytt fra innsending-ID til inntektsmelding-ID ved lagring av journalpost-ID

- apps/api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/hentforespoersel/HentForespoerselResponse.kt
- apps/api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/hentforespoersel/HentForespoerselRoute.kt
- apps/api/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/hentforespoersel/HentForespoerselRouteKtTest.kt
Fjerner `opprettetUpresisIkkeBruk`, som ikke lenger er i bruk.
Fjerner også `success` og `failure`, som aldri ble tatt i bruk, og som er utdatert som løsning.
> Fjern utdatert responsfelt

- apps/api/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/hentforespoersel/HentForespoerselRouteKtTest.kt
- apps/felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/domene/Forespoersel.kt
- apps/felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/domene/ForespoerselFraBro.kt
- apps/felles/src/testFixtures/kotlin/no/nav/helsearbeidsgiver/felles/test/mock/MockForespoersel.kt
- apps/forespoersel-mottatt/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/forespoerselmottatt/ForespoerselMottattRiverTest.kt
- apps/helsebro/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/helsebro/MockUtils.kt
- apps/integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/BerikInntektsmeldingServiceIT.kt
- apps/integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/ForespoerselMottattIT.kt
- apps/integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/InnsendingIT.kt
- apps/integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/InnsendingServiceIT.kt
- apps/integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/mock/MockData.kt
Dette feltet ble sendt til frontend for å kunne aktivere spørreskjema etter purring.
> Fjern utdatert felt fra forespoersel

- apps/felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/Key.kt
- apps/joark/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/dokument/PdfDokument.kt
- apps/joark/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/dokument/PdfDokumentTest.kt
PDFen i gosys viser ikke begrunnelser for redusert lønn i AGP om det ikke er noen AGP i inntektsmeldingen.
Denne PRen fikser dette.
> Fiks PDF viser ikke begrunnelse når ingen agp

- apps/distribusjon/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/distribusjon/DistribusjonRiver.kt
- apps/distribusjon/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/distribusjon/DistribusjonRiverTest.kt
Uten en (god) nøkkel i `ProducerRecord` så kan vi ikke garantere rekkefølgen på meldinger som sendes på Kafka-strømmen. Denne har gått under radaren til nå, men ble avslørt da den nylig førte til en prodfeil der to IM-er hadde feil rekkefølge.
> Distribuer inntektsmeldinger med garantert rekkefølge

- apps/distribusjon/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/distribusjon/DistribusjonRiver.kt
- apps/distribusjon/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/distribusjon/DistribusjonRiverTest.kt
- apps/felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/kafka/Producer.kt
- apps/felles/src/test/kotlin/no/nav/helsearbeidsgiver/felles/kafka/ProducerTest.kt
- apps/forespoersel-marker-besvart/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/forespoerselmarkerbesvart/MarkerForespoerselBesvartRiver.kt
- apps/forespoersel-marker-besvart/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/forespoerselmarkerbesvart/MarkerForespoerselBesvartRiverTest.kt
- apps/helsebro/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/helsebro/HentForespoerslerForVedtaksperiodeIdListeRiver.kt
- apps/helsebro/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/helsebro/TrengerForespoerselRiver.kt
- apps/helsebro/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/helsebro/HentForespoerslerForVedtaksperiodeIdListeRiverTest.kt
- apps/helsebro/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/helsebro/TrengerForespoerselRiverTest.kt
- apps/integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/InnsendingIT.kt
- apps/integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/LagreSelvbestemtIT.kt
- apps/integrasjonstest/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/integrasjonstest/utils/EndToEndTest.kt
Fjerner en innebygget catch av exceptions i producer. Den har tidligere vært brukt til å ignorere feil i flyter som involverer brukere og dermed er lette å gjeninitiere. Nå er producer sentral i den asynkrone delen av Simba, og da synes jeg den innebygde catchen ble litt for skummel, da man fort kan bruke den feil og svelge viktige exceptions.
> La producer feile ved problemer

- apps/api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/hentforespoersel/HentForespoerselResponse.kt
- apps/api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/hentforespoersel/HentForespoerselRoute.kt
- apps/api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/inntekt/InntektResponse.kt
- apps/api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/inntekt/InntektRoute.kt
- apps/api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/inntektselvbestemt/InntektSelvbestemtResponse.kt
- apps/api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/inntektselvbestemt/InntektSelvbestemtRoute.kt
- apps/api/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/hentforespoersel/HentForespoerselRouteKtTest.kt
- apps/api/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/inntekt/InntektRouteKtTest.kt
- apps/api/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/inntektselvbestemt/InntektSelvbestemtRouteKtTest.kt
- apps/felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/utils/MoneyUtils.kt
- apps/felles/src/test/kotlin/no/nav/helsearbeidsgiver/felles/utils/MoneyUtilsKtTest.kt
Gjør responsen for preutfylling, og et par andre mindre endepunkter, mer enhetlig med resten av API-et mot frontend.
> Forbedre respons mot frontend for henting av preutfyllingsinfo

- apps/felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/metrics/Metrics.kt
- apps/joark/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/JournalfoerImRiver.kt
- apps/joark/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/TilDokumenter.kt
- apps/joark/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/JournalfoerImRiverTest.kt
- apps/joark/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/TilDokumenterKtTest.kt
Dette vil gjøre det lettere å finne den ene fra den andre.
> Bruk inntektsmelding-ID som journalføringsreferanse

- apps/bro-spinn/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/brospinn/HttpUtils.kt
- apps/bro-spinn/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/brospinn/MockSpinnKlient.kt
- apps/bro-spinn/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/brospinn/SpinnKlientTest.kt
Nåværende konfigurasjon støtter ikke retry ved timeouts ordentlig.
> Spinn-klient: Fiks retry ved timeout

- apps/api/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/hentselvbestemtim/HentSelvbestemtImRouteKtTest.kt
- apps/db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/river/LagreJournalpostIdRiver.kt
- apps/db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/river/OppdaterImSomProsessertRiver.kt
- apps/db/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/river/OppdaterImSomProsessertRiverTest.kt
- apps/distribusjon/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/distribusjon/DistribusjonRiver.kt
- apps/joark/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/JournalfoerImRiver.kt
- apps/selvbestemt-lagre-im-service/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/selvbestemtlagreimservice/LagreSelvbestemtImService.kt
- apps/selvbestemt-lagre-im-service/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/selvbestemtlagreimservice/ArbeidsforholdInnenforPeriodeKtTest.kt
- apps/selvbestemt-lagre-im-service/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/selvbestemtlagreimservice/LagreSelvbestemtImServiceTest.kt
- gradle.properties
I denne PRen brukes IM domene modell snapshot som har 2 nye typer: `fisker` og `utenArbeidsforhold`
Har ikke koblet opp til et API endepukt så er ikke mulig å teste i dev enda.
Eneste nye logikken så langt er i [LagreSelvbestemtImService.kt](https://github.com/navikt/helsearbeidsgiver-inntektsmelding/compare/fisker-selvbestemt?expand=1#diff-2a30fdd1cf30eb3cc4defaebaca159b60350d698e7bb4ef39413a4eed6be8a39):
`val harIngenArbeidsforhold = inntektsmelding.type is Inntektsmelding.Type.Fisker || inntektsmelding.type is Inntektsmelding.Type.UtenArbeidsforhold`
Om variabelen harIngenArbeidshold er true ignorerer vi om `sykeperioder.aktivtArbeidsforholdIPeriode(steg1.arbeidsforhold)` er `false`
___________
Alle de andre endringene kommer fra å utfylle when(inntektsmelding.type) og tester
> Legger til støtte for IM type Fisker og UtenArbeidsforhold

- apps/inntekt/gradle.properties
- apps/inntekt/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/inntekt/App.kt
Setter cachetid til 10 min for å gi mulighet til å treffe flere ganger utfylling av skjema, ved reinnlasting og endring av AGP. Dette er et av de tyngre kallene vi har, men vi vil heller ikke cache for lenge i tilfelle dataene endres.
Cachestørrelse basert på https://logs.adeo.no/app/r/s/Bfz0o.
> Bruk inntektklient med cache, retry og timeout

- apps/notifikasjon/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/ArbeidsgiverNotifikasjonKlientUtils.kt
- apps/notifikasjon/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/river/FerdigstillForespoerselSakOgOppgaveRiverTest.kt
- apps/notifikasjon/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/notifikasjon/river/UtgaattForespoerselRiverTest.kt
Som `Deprecated`-annotasjonen sier så er ble `MERKELAPP_GAMMEL ` utdatert siden 21.05.2024. Da ble den erstattet med `MERKELAPP`. Siden hver Fager-sak har en levetid på 13 måneder, så vet vi at alle saker med den gamle merkelappen nå har blitt slettet. Det gjør at vi kan fjerne koden som prøver å bruke den gamle merkelappen dersom endring av saken feiler når vi bruker den nye merkelappen.
🚮
> Arbeidsgivernotifikasjon: Fjern utdatert merkelapp

- config/notifikasjon/dev-gcp.yml
LPS har etterlyst muligheten for å se / sende inn manuelt i test. 
Vi har lagt til ekstern.dev.nav.no i frontend, slik at simba kan nåes både via nav intern url og åpen ekstern url. 
Endrer notifikasjonslinken for ny sak/oppgave til å peke til ekstern-url, slik at LPS kan navigere sømløst fra fager-sak / oppgave inn til simba. 
For oss som er interne kan vi uansett bruke disse URLene på kryss og tvers (gå fra intern til ekstern uten ny innlogging).
> bytt fra intern til ekstern.dev.nav.no i notifikasjon-linker i dev

- apps/joark/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/TilDokumenter.kt
- apps/joark/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/dokument/PdfDokument.kt
- apps/joark/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/TilDokumenterKtTest.kt
- apps/joark/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/joark/dokument/PdfDokumentTest.kt
Generer pdf tittel basert på inntektsmeldingtype.
Genrer dokumentbeskrivelse i joark basert på inntektsmeldingtype.
Dette gjør at saksbehandler ser at det gjelder UtenArbeidsforhold og fisker m/ hyre i gosys
> Dokumentbeskrivelse og pdf tittel for fisker og uten arbeidsforhold

- apps/aktiveorgnrservice/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/aktiveorgnrservice/App.kt
- apps/db/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/db/App.kt
- apps/distribusjon/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/distribusjon/App.kt
- apps/feil-behandler/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/feilbehandler/App.kt
- apps/felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/rapidsrivers/LifecycleUtils.kt
- apps/forespoersel-marker-besvart/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/forespoerselmarkerbesvart/App.kt
- apps/helsebro/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/helsebro/App.kt
- apps/innsending/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/innsending/App.kt
- apps/inntekt-selvbestemt-service/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/inntektselvbestemtservice/App.kt
- apps/inntektservice/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/inntektservice/App.kt
- apps/selvbestemt-hent-im-service/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/selvbestemthentimservice/App.kt
- apps/selvbestemt-lagre-im-service/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/selvbestemtlagreimservice/App.kt
- apps/tilgangservice/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/tilgangservice/App.kt
- apps/trengerservice/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/trengerservice/App.kt
Dette er for å hindre apper å bli drept fordi de ikke svarer på helsesjekker mens de jobber med databasemigreringer.
> Kjør databasemigrering etter appens startsignal, men før klarsignal

- apps/api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/RedisPoller.kt
- apps/api/src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/RedisPollerTest.kt
Bakgrunn: Tregheter mot inntekt gjør at inntekt-klienten gjør retries, men summen av all ventetiden blir større enn dagens maxVentetid satt i redisPoller (var 5500 ms).
Dermed resulterer http-kallet fra bruker i en 500-feil fra API etter 5.5 sekunder, når vi egentlig skulle gi tilbake et "partial skjema" uten inntekt utfylt. 
Ved å øke fra 10 til 15 retries, økes max ventetid mot redis fra 5.5 sekunder til 12 sekunder, og vi vil forhåpentligvis se færre 500-feil til frontend ved ikke-kritiske timeouts.
> redisPoller: Øker til 15 retries (gir max ventetid for api 12 sekunder)

- utils/rapids-and-rivers/src/main/kotlin/no/nav/hag/simba/utils/rr/service/Service.kt
- utils/rapids-and-rivers/src/main/kotlin/no/nav/hag/simba/utils/rr/service/ServiceRiver.kt
- utils/rapids-and-rivers/src/test/kotlin/no/nav/hag/simba/utils/rr/service/ServiceRiverStatefulTest.kt
Når en melding kommer inn til en stateful service så legges alt som ligger i Redis til på rotnivå. Endrer dette til også å legge Redis-data i nested data (aka under `Key.DATA`). Det er kun nested data som blir lagret i Redis.
Endringen fikser en liten feil vi har i dag, som sjeldent oppstår. Noen stateful servicer starter med å samtidig sende ut flere meldinger hvor man forventer en respons (som kun stateful kan håndtere). Når alle svarene er mottatt, så involverer resten av stegene kun enkeltmeldinger. Da går servicen over til å bruke en stateless framgangsmåte, men det har ikke fungert ettersom pga. manglende felt fra Redis i nested data. Det løses nå.
> Legg Redis-data i nested data for stateful service
